#include <assert.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>

static char *db[26][26][26];
static bool setup = false;

#define CTOI(c) c - 'A'
#define INDEX_DB(code) db[CTOI(code[0])][CTOI(code[1])][CTOI(code[2])]
#define STATION(name, code) INDEX_DB(code) = name

static void init(void);

char *crs(char *code) {
  assert(code && strlen(code) >= 3);

  if (!setup) {
    init();

    setup = true;
  }

  code[0] = toupper(code[0]);
  code[1] = toupper(code[1]);
  code[2] = toupper(code[2]);

  return INDEX_DB(code);
}

static void init(void) {
  STATION("Abbey Wood", "ABW");
  STATION("Aber", "ABE");
  STATION("Abercynon", "ACY");
  STATION("Aberdare", "ABA");
  STATION("Aberdeen", "ABD");
  STATION("Aberdour", "AUR");
  STATION("Aberdovey", "AVY");
  STATION("Abererch", "ABH");
  STATION("Abergavenny", "AGV");
  STATION("Abergele & Pensarn", "AGL");
  STATION("Aberystwyth", "AYW");
  STATION("Accrington", "ACR");
  STATION("Achanalt", "AAT");
  STATION("Achnasheen", "ACN");
  STATION("Achnashellach", "ACH");
  STATION("Acklington", "ACK");
  STATION("Acle", "ACL");
  STATION("Acocks Green", "ACG");
  STATION("Acton Bridge (Cheshire)", "ACB");
  STATION("Acton Central", "ACC");
  STATION("Acton Main Line", "AML");
  STATION("Adderley Park", "ADD");
  STATION("Addiewell", "ADW");
  STATION("Addlestone", "ASN");
  STATION("Adisham", "ADM");
  STATION("Adlington (Cheshire)", "ADC");
  STATION("Adlington (Lancs)", "ADL");
  STATION("Adwick", "AWK");
  STATION("Aigburth", "AIG");
  STATION("Ainsdale", "ANS");
  STATION("Aintree", "AIN");
  STATION("Airbles", "AIR");
  STATION("Airdrie", "ADR");
  STATION("Albany Park", "AYP");
  STATION("Albrighton", "ALB");
  STATION("Alderley Edge", "ALD");
  STATION("Aldermaston", "AMT");
  STATION("Aldershot", "AHT");
  STATION("Aldrington", "AGT");
  STATION("Alexandra Palace", "AAP");
  STATION("Alexandra Parade", "AXP");
  STATION("Alexandria", "ALX");
  STATION("Alfreton", "ALF");
  STATION("Allens West", "ALW");
  STATION("Alloa", "ALO");
  STATION("Alness", "ASS");
  STATION("Alnmouth", "ALM");
  STATION("Alresford (Essex)", "ALR");
  STATION("Alsager", "ASG");
  STATION("Althorne (Essex)", "ALN");
  STATION("Althorpe", "ALP");
  STATION("Altnabreac", "ABC");
  STATION("Alton", "AON");
  STATION("Altrincham", "ALT");
  STATION("Alvechurch", "ALV");
  STATION("Ambergate", "AMB");
  STATION("Amberley", "AMY");
  STATION("Amersham", "AMR");
  STATION("Ammanford", "AMF");
  STATION("Ancaster", "ANC");
  STATION("Anderston", "AND");
  STATION("Andover", "ADV");
  STATION("Anerley", "ANZ");
  STATION("Angmering", "ANG");
  STATION("Annan", "ANN");
  STATION("Anniesland", "ANL");
  STATION("Ansdell & Fairhaven", "AFV");
  STATION("Apperley Bridge", "APY");
  STATION("Appleby", "APP");
  STATION("Appledore (Kent)", "APD");
  STATION("Appleford", "APF");
  STATION("Appley Bridge", "APB");
  STATION("Apsley", "APS");
  STATION("Arbroath", "ARB");
  STATION("Ardgay", "ARD");
  STATION("Ardlui", "AUI");
  STATION("Ardrossan Harbour", "ADS");
  STATION("Ardrossan South Beach", "ASB");
  STATION("Ardrossan Town", "ADN");
  STATION("Ardwick", "ADK");
  STATION("Argyle Street", "AGS");
  STATION("Arisaig", "ARG");
  STATION("Arlesey", "ARL");
  STATION("Armadale (West Lothian)", "ARM");
  STATION("Armathwaite", "AWT");
  STATION("Arnside", "ARN");
  STATION("Arram", "ARR");
  STATION("Arrochar & Tarbet", "ART");
  STATION("Arundel", "ARU");
  STATION("Ascot (Berks)", "ACT");
  STATION("Ascott-under-Wychwood", "AUW");
  STATION("Ash Vale", "AHV");
  STATION("Ash", "ASH");
  STATION("Ashburys", "ABY");
  STATION("Ashchurch for Tewkesbury", "ASC");
  STATION("Ashfield", "ASF");
  STATION("Ashford (Surrey)", "AFS");
  STATION("Ashford International (Eurostar)", "ASI");
  STATION("Ashford International", "AFK");
  STATION("Ashley", "ASY");
  STATION("Ashtead", "AHD");
  STATION("Ashton-under-Lyne", "AHN");
  STATION("Ashurst (Kent)", "AHS");
  STATION("Ashurst New Forest", "ANF");
  STATION("Ashwell & Morden", "AWM");
  STATION("Askam", "ASK");
  STATION("Aslockton", "ALK");
  STATION("Aspatria", "ASP");
  STATION("Aspley Guise", "APG");
  STATION("Aston", "AST");
  STATION("Atherstone", "ATH");
  STATION("Atherton", "ATN");
  STATION("Attadale", "ATT");
  STATION("Attenborough", "ATB");
  STATION("Attleborough", "ATL");
  STATION("Auchinleck", "AUK");
  STATION("Audley End", "AUD");
  STATION("Aughton Park", "AUG");
  STATION("Aviemore", "AVM");
  STATION("Avoncliff", "AVF");
  STATION("Avonmouth", "AVN");
  STATION("Axminster", "AXM");
  STATION("Aylesbury Vale Parkway", "AVP");
  STATION("Aylesbury", "AYS");
  STATION("Aylesford", "AYL");
  STATION("Aylesham", "AYH");
  STATION("Ayr", "AYR");
  STATION("Bache", "BAC");
  STATION("Baglan", "BAJ");
  STATION("Bagshot", "BAG");
  STATION("Baildon", "BLD");
  STATION("Baillieston", "BIO");
  STATION("Balcombe", "BAB");
  STATION("Baldock", "BDK");
  STATION("Balham", "BAL");
  STATION("Balloch", "BHC");
  STATION("Balmossie", "BSI");
  STATION("Bamber Bridge", "BMB");
  STATION("Bamford", "BAM");
  STATION("Banavie", "BNV");
  STATION("Banbury", "BAN");
  STATION("Bangor (Gwynedd)", "BNG");
  STATION("Bank Hall", "BAH");
  STATION("Banstead", "BAD");
  STATION("Barassie", "BSS");
  STATION("Barbican", "ZBB");
  STATION("Bardon Mill", "BLL");
  STATION("Bare Lane", "BAR");
  STATION("Bargeddie", "BGI");
  STATION("Bargoed", "BGD");
  STATION("Barking", "BKG");
  STATION("Barlaston", "BRT");
  STATION("Barming", "BMG");
  STATION("Barmouth", "BRM");
  STATION("Barnehurst", "BNH");
  STATION("Barnes Bridge", "BNI");
  STATION("Barnes", "BNS");
  STATION("Barnetby", "BTB");
  STATION("Barnham", "BAA");
  STATION("Barnhill", "BNL");
  STATION("Barnsley", "BNY");
  STATION("Barnstaple", "BNP");
  STATION("Barnt Green", "BTG");
  STATION("Barrhead", "BRR");
  STATION("Barrhill", "BRL");
  STATION("Barrow Haven", "BAV");
  STATION("Barrow-Upon-Soar", "BWS");
  STATION("Barrow-in-Furness", "BIF");
  STATION("Barry Docks", "BYD");
  STATION("Barry Island", "BYI");
  STATION("Barry Links", "BYL");
  STATION("Barry", "BRY");
  STATION("Barton-on-Humber", "BAU");
  STATION("Basildon", "BSO");
  STATION("Basingstoke", "BSK");
  STATION("Bat & Ball", "BBL");
  STATION("Bath Spa", "BTH");
  STATION("Bathgate", "BHG");
  STATION("Batley", "BTL");
  STATION("Battersby", "BTT");
  STATION("Battersea Park", "BAK");
  STATION("Battle", "BAT");
  STATION("Battlesbridge", "BLB");
  STATION("Bayford", "BAY");
  STATION("Beaconsfield", "BCF");
  STATION("Bearley", "BER");
  STATION("Bearsden", "BRN");
  STATION("Bearsted", "BSD");
  STATION("Beasdale", "BSL");
  STATION("Beaulieu Road", "BEU");
  STATION("Beauly", "BEL");
  STATION("Bebington", "BEB");
  STATION("Beccles", "BCC");
  STATION("Beckenham Hill", "BEC");
  STATION("Beckenham Junction", "BKJ");
  STATION("Bedford St Johns", "BSJ");
  STATION("Bedford", "BDM");
  STATION("Bedhampton", "BDH");
  STATION("Bedminster", "BMT");
  STATION("Bedworth", "BEH");
  STATION("Bedwyn", "BDW");
  STATION("Beeston", "BEE");
  STATION("Bekesbourne", "BKS");
  STATION("Belle Vue", "BLV");
  STATION("Bellgrove", "BLG");
  STATION("Bellingham", "BGM");
  STATION("Bellshill", "BLH");
  STATION("Belmont", "BLM");
  STATION("Belper", "BLP");
  STATION("Beltring", "BEG");
  STATION("Belvedere", "BVD");
  STATION("Bempton", "BEM");
  STATION("Ben Rhydding", "BEY");
  STATION("Benfleet", "BEF");
  STATION("Bentham", "BEN");
  STATION("Bentley (Hants)", "BTY");
  STATION("Bentley (South Yorks)", "BYK");
  STATION("Bere Alston", "BAS");
  STATION("Bere Ferrers", "BFE");
  STATION("Berkhamsted", "BKM");
  STATION("Berkswell", "BKW");
  STATION("Bermuda Park", "BEP");
  STATION("Berney Arms", "BYA");
  STATION("Berry Brow", "BBW");
  STATION("Berrylands", "BRS");
  STATION("Berwick (Sussex)", "BRK");
  STATION("Berwick-upon-Tweed", "BWK");
  STATION("Bescar Lane", "BES");
  STATION("Bescot Stadium", "BSC");
  STATION("Betchworth", "BTO");
  STATION("Bethnal Green", "BET");
  STATION("Betws-y-Coed", "BYC");
  STATION("Beverley", "BEV");
  STATION("Bexhill", "BEX");
  STATION("Bexley", "BXY");
  STATION("Bexleyheath", "BXH");
  STATION("Bicester North", "BCS");
  STATION("Bicester Village", "BIT");
  STATION("Bickley", "BKL");
  STATION("Bidston", "BID");
  STATION("Biggleswade", "BIW");
  STATION("Bilbrook", "BBK");
  STATION("Billericay", "BIC");
  STATION("Billingham (Cleveland)", "BIL");
  STATION("Billingshurst", "BIG");
  STATION("Bingham", "BIN");
  STATION("Bingley", "BIY");
  STATION("Birchgrove", "BCG");
  STATION("Birchington-on-sea", "BCH");
  STATION("Birchwood", "BWD");
  STATION("Birkbeck", "BIK");
  STATION("Birkdale", "BDL");
  STATION("Birkenhead Central", "BKC");
  STATION("Birkenhead Hamilton Square", "BKQ");
  STATION("Birkenhead North", "BKN");
  STATION("Birkenhead Park", "BKP");
  STATION("Birmingham International", "BHI");
  STATION("Birmingham Moor Street", "BMO");
  STATION("Birmingham New Street", "BHM");
  STATION("Birmingham Snow Hill", "BSW");
  STATION("Bishop Auckland", "BIA");
  STATION("Bishopbriggs", "BBG");
  STATION("Bishops Stortford", "BIS");
  STATION("Bishopstone (Sussex)", "BIP");
  STATION("Bishopton (Strathclyde)", "BPT");
  STATION("Bitterne", "BTE");
  STATION("Blackburn", "BBN");
  STATION("Blackheath", "BKH");
  STATION("Blackhorse Road", "BHO");
  STATION("Blackpool North", "BPN");
  STATION("Blackpool Pleasure Beach", "BPB");
  STATION("Blackpool South", "BPS");
  STATION("Blackridge", "BKR");
  STATION("Blackrod", "BLK");
  STATION("Blackwater", "BAW");
  STATION("Blaenau Ffestiniog", "BFF");
  STATION("Blair Atholl", "BLA");
  STATION("Blairhill", "BAI");
  STATION("Blake Street", "BKT");
  STATION("Blakedown", "BKD");
  STATION("Blantyre", "BLT");
  STATION("Blaydon", "BLO");
  STATION("Bleasby", "BSB");
  STATION("Bletchley", "BLY");
  STATION("Bloxwich North", "BWN");
  STATION("Bloxwich", "BLX");
  STATION("Blundellsands & Crosby", "BLN");
  STATION("Blythe Bridge", "BYB");
  STATION("Bodmin Parkway", "BOD");
  STATION("Bodorgan", "BOR");
  STATION("Bognor Regis", "BOG");
  STATION("Bogston", "BGS");
  STATION("Bolton", "BON");
  STATION("Bolton-Upon-Dearne", "BTD");
  STATION("Bookham", "BKA");
  STATION("Bootle (Cumbria)", "BOC");
  STATION("Bootle New Strand", "BNW");
  STATION("Bootle Oriel Road", "BOT");
  STATION("Bordesley", "BBS");
  STATION("Borough Green & Wrotham", "BRG");
  STATION("Borth", "BRH");
  STATION("Bosham", "BOH");
  STATION("Boston", "BSN");
  STATION("Botley", "BOE");
  STATION("Bottesford", "BTF");
  STATION("Bourne End", "BNE");
  STATION("Bournemouth", "BMH");
  STATION("Bournville", "BRV");
  STATION("Bow Brickhill", "BWB");
  STATION("Bowes Park", "BOP");
  STATION("Bowling", "BWG");
  STATION("Box Hill & Westhumble", "BXW");
  STATION("Bracknell", "BCE");
  STATION("Bradford Forster Square", "BDQ");
  STATION("Bradford Interchange", "BDI");
  STATION("Bradford-on-Avon", "BOA");
  STATION("Brading", "BDN");
  STATION("Braintree Freeport", "BTP");
  STATION("Braintree", "BTR");
  STATION("Bramhall", "BML");
  STATION("Bramley (Hants)", "BMY");
  STATION("Bramley (W Yorks)", "BLE");
  STATION("Brampton (Cumbria)", "BMP");
  STATION("Brampton (Suffolk)", "BRP");
  STATION("Branchton", "BCN");
  STATION("Brandon", "BND");
  STATION("Branksome", "BSM");
  STATION("Braystones (Cumbria)", "BYS");
  STATION("Bredbury", "BDY");
  STATION("Breich", "BRC");
  STATION("Brentford", "BFD");
  STATION("Brentwood", "BRE");
  STATION("Bricket Wood", "BWO");
  STATION("Bridge of Allan", "BEA");
  STATION("Bridge of Orchy", "BRO");
  STATION("Bridgend", "BGN");
  STATION("Bridgeton", "BDG");
  STATION("Bridgwater", "BWT");
  STATION("Bridlington", "BDT");
  STATION("Brierfield", "BRF");
  STATION("Brigg", "BGG");
  STATION("Brighouse", "BGH");
  STATION("Brighton (East Sussex)", "BTN");
  STATION("Brimsdown", "BMD");
  STATION("Brinnington", "BNT");
  STATION("Bristol Parkway", "BPW");
  STATION("Bristol Temple Meads", "BRI");
  STATION("Brithdir", "BHD");
  STATION("Briton Ferry", "BNF");
  STATION("Brixton", "BRX");
  STATION("Broad Green", "BGE");
  STATION("Broadbottom", "BDB");
  STATION("Broadstairs", "BSR");
  STATION("Brockenhurst", "BCU");
  STATION("Brockholes", "BHS");
  STATION("Brockley", "BCY");
  STATION("Bromborough Rake", "BMR");
  STATION("Bromborough", "BOM");
  STATION("Bromley Cross (Lancs)", "BMC");
  STATION("Bromley North", "BMN");
  STATION("Bromley South", "BMS");
  STATION("Bromsgrove", "BMV");
  STATION("Brondesbury Park", "BSP");
  STATION("Brondesbury", "BSY");
  STATION("Brookmans Park", "BPK");
  STATION("Brookwood", "BKO");
  STATION("Broome", "BME");
  STATION("Broomfleet", "BMF");
  STATION("Brora", "BRA");
  STATION("Brough", "BUH");
  STATION("Broughty Ferry", "BYF");
  STATION("Broxbourne", "BXB");
  STATION("Bruce Grove", "BCV");
  STATION("Brundall Gardens", "BGA");
  STATION("Brundall", "BDA");
  STATION("Brunstane", "BSU");
  STATION("Brunswick", "BRW");
  STATION("Bruton", "BRU");
  STATION("Bryn", "BYN");
  STATION("Buckenham (Norfolk)", "BUC");
  STATION("Buckley", "BCK");
  STATION("Bucknell", "BUK");
  STATION("Buckshaw Parkway", "BSV");
  STATION("Bugle", "BGL");
  STATION("Builth Road", "BHR");
  STATION("Bulwell", "BLW");
  STATION("Bures", "BUE");
  STATION("Burgess Hill", "BUG");
  STATION("Burley Park", "BUY");
  STATION("Burley-in-Wharfedale", "BUW");
  STATION("Burnage", "BNA");
  STATION("Burneside (Cumbria)", "BUD");
  STATION("Burnham (Bucks)", "BNM");
  STATION("Burnham-on-Crouch", "BUU");
  STATION("Burnley Barracks", "BUB");
  STATION("Burnley Central", "BNC");
  STATION("Burnley Manchester Road", "BYM");
  STATION("Burnside (Strathclyde)", "BUI");
  STATION("Burntisland", "BTS");
  STATION("Burscough Bridge", "BCB");
  STATION("Burscough Junction", "BCJ");
  STATION("Bursledon", "BUO");
  STATION("Burton Joyce", "BUJ");
  STATION("Burton-on-Trent", "BUT");
  STATION("Bury St Edmunds", "BSE");
  STATION("Busby", "BUS");
  STATION("Bush Hill Park", "BHK");
  STATION("Bushey", "BSH");
  STATION("Butlers Lane", "BUL");
  STATION("Buxted", "BXD");
  STATION("Buxton", "BUX");
  STATION("Byfleet & New Haw", "BFN");
  STATION("Bynea", "BYE");
  STATION("Cadoxton", "CAD");
  STATION("Caergwrle", "CGW");
  STATION("Caerphilly", "CPH");
  STATION("Caersws", "CWS");
  STATION("Caldercruix", "CAC");
  STATION("Caldicot", "CDT");
  STATION("Caledonian Rd & Barnsbury", "CIR");
  STATION("Calstock", "CSK");
  STATION("Cam & Dursley", "CDU");
  STATION("Camberley", "CAM");
  STATION("Camborne", "CBN");
  STATION("Cambridge Heath", "CBH");
  STATION("Cambridge North", "CMB");
  STATION("Cambridge", "CBG");
  STATION("Cambuslang", "CBL");
  STATION("Camden Road", "CMD");
  STATION("Camelon", "CMO");
  STATION("Cameron Bridge", "CBX");
  STATION("Canada Water", "ZCW");
  STATION("Canley", "CNL");
  STATION("Cannock", "CAO");
  STATION("Canonbury", "CNN");
  STATION("Canterbury East", "CBE");
  STATION("Canterbury West", "CBW");
  STATION("Cantley", "CNY");
  STATION("Capenhurst", "CPU");
  STATION("Carbis Bay", "CBB");
  STATION("Cardenden", "CDD");
  STATION("Cardiff Bay", "CDB");
  STATION("Cardiff Central", "CDF");
  STATION("Cardiff Queen Street", "CDQ");
  STATION("Cardonald", "CDO");
  STATION("Cardross", "CDR");
  STATION("Carfin", "CRF");
  STATION("Cark & Cartmel", "CAK");
  STATION("Carlisle", "CAR");
  STATION("Carlton", "CTO");
  STATION("Carluke", "CLU");
  STATION("Carmarthen", "CMN");
  STATION("Carmyle", "CML");
  STATION("Carnforth", "CNF");
  STATION("Carnoustie", "CAN");
  STATION("Carntyne", "CAY");
  STATION("Carpenders Park", "CPK");
  STATION("Carrbridge", "CAG");
  STATION("Carshalton Beeches", "CSB");
  STATION("Carshalton", "CSH");
  STATION("Carstairs", "CRS");
  STATION("Cartsdyke", "CDY");
  STATION("Castle Bar Park", "CBP");
  STATION("Castle Cary", "CLC");
  STATION("Castleford", "CFD");
  STATION("Castleton (Manchester)", "CAS");
  STATION("Castleton Moor", "CSM");
  STATION("Caterham", "CAT");
  STATION("Catford Bridge", "CFB");
  STATION("Catford", "CTF");
  STATION("Cathays", "CYS");
  STATION("Cathcart", "CCT");
  STATION("Cattal", "CTL");
  STATION("Causeland", "CAU");
  STATION("Cefn-y-Bedd", "CYB");
  STATION("Chadwell Heath", "CTH");
  STATION("Chafford Hundred Lakeside", "CFH");
  STATION("Chalfont & Latimer", "CFO");
  STATION("Chalkwell", "CHW");
  STATION("Chandlers Ford", "CFR");
  STATION("Chapel-en-le-Frith", "CEF");
  STATION("Chapelton (Devon)", "CPN");
  STATION("Chapeltown (South Yorks)", "CLN");
  STATION("Chappel & Wakes Colne", "CWC");
  STATION("Charing (Kent)", "CHG");
  STATION("Charing Cross (Glasgow)", "CHC");
  STATION("Charlbury", "CBY");
  STATION("Charlton", "CTN");
  STATION("Chartham", "CRT");
  STATION("Chassen Road", "CSR");
  STATION("Chatelherault", "CTE");
  STATION("Chatham", "CTM");
  STATION("Chathill", "CHT");
  STATION("Cheadle Hulme", "CHU");
  STATION("Cheam", "CHE");
  STATION("Cheddington", "CED");
  STATION("Chelford (Cheshire)", "CEL");
  STATION("Chelmsford", "CHM");
  STATION("Chelsfield", "CLD");
  STATION("Cheltenham Spa", "CNM");
  STATION("Chepstow", "CPW");
  STATION("Cherry Tree", "CYT");
  STATION("Chertsey", "CHY");
  STATION("Cheshunt", "CHN");
  STATION("Chessington North", "CSN");
  STATION("Chessington South", "CSS");
  STATION("Chester Road", "CRD");
  STATION("Chester", "CTR");
  STATION("Chester-le-Street", "CLS");
  STATION("Chesterfield", "CHD");
  STATION("Chestfield & Swalecliffe", "CSW");
  STATION("Chetnole", "CNO");
  STATION("Chichester", "CCH");
  STATION("Chilham", "CIL");
  STATION("Chilworth", "CHL");
  STATION("Chingford", "CHI");
  STATION("Chinley", "CLY");
  STATION("Chippenham", "CPM");
  STATION("Chipstead", "CHP");
  STATION("Chirk", "CRK");
  STATION("Chislehurst", "CIT");
  STATION("Chiswick", "CHK");
  STATION("Cholsey", "CHO");
  STATION("Chorley", "CRL");
  STATION("Chorleywood", "CLW");
  STATION("Christchurch", "CHR");
  STATION("Christs Hospital", "CHH");
  STATION("Church & Oswaldtwistle", "CTW");
  STATION("Church Fenton", "CHF");
  STATION("Church Stretton", "CTT");
  STATION("Cilmeri", "CIM");
  STATION("City Thameslink", "CTK");
  STATION("Clacton-on-Sea", "CLT");
  STATION("Clandon", "CLA");
  STATION("Clapham (North Yorkshire)", "CPY");
  STATION("Clapham High Street", "CLP");
  STATION("Clapham Junction", "CLJ");
  STATION("Clapton", "CPT");
  STATION("Clarbeston Road", "CLR");
  STATION("Clarkston", "CKS");
  STATION("Claverdon", "CLV");
  STATION("Claygate", "CLG");
  STATION("Cleethorpes", "CLE");
  STATION("Cleland", "CEA");
  STATION("Clifton (Manchester)", "CLI");
  STATION("Clifton Down", "CFN");
  STATION("Clitheroe", "CLH");
  STATION("Clock House", "CLK");
  STATION("Clunderwen", "CUW");
  STATION("Clydebank", "CYK");
  STATION("Coatbridge Central", "CBC");
  STATION("Coatbridge Sunnyside", "CBS");
  STATION("Coatdyke", "COA");
  STATION("Cobham & Stoke d'Abernon", "CSD");
  STATION("Codsall", "CSL");
  STATION("Cogan", "CGN");
  STATION("Colchester Town", "CET");
  STATION("Colchester", "COL");
  STATION("Coleshill Parkway", "CEH");
  STATION("Collingham", "CLM");
  STATION("Collington", "CLL");
  STATION("Colne", "CNE");
  STATION("Colwall", "CWL");
  STATION("Colwyn Bay", "CWB");
  STATION("Combe (Oxon)", "CME");
  STATION("Commondale", "COM");
  STATION("Congleton", "CNG");
  STATION("Conisbrough", "CNS");
  STATION("Connel Ferry", "CON");
  STATION("Conon Bridge", "CBD");
  STATION("Cononley", "CEY");
  STATION("Conway Park", "CNP");
  STATION("Conwy", "CNW");
  STATION("Cooden Beach", "COB");
  STATION("Cookham", "COO");
  STATION("Cooksbridge", "CBR");
  STATION("Coombe Junction Halt", "COE");
  STATION("Copplestone", "COP");
  STATION("Corbridge", "CRB");
  STATION("Corby", "COR");
  STATION("Corfe Castle", "CFC");
  STATION("Corkerhill", "CKH");
  STATION("Corkickle", "CKL");
  STATION("Corpach", "CPA");
  STATION("Corrour", "CRR");
  STATION("Coryton", "COY");
  STATION("Coseley", "CSY");
  STATION("Cosford", "COS");
  STATION("Cosham", "CSA");
  STATION("Cottingham", "CGM");
  STATION("Cottingley", "COT");
  STATION("Coulsdon South", "CDS");
  STATION("Coulsdon Town", "CDN");
  STATION("Coventry Arena", "CAA");
  STATION("Coventry", "COV");
  STATION("Cowden (Kent)", "CWN");
  STATION("Cowdenbeath", "COW");
  STATION("Cradley Heath", "CRA");
  STATION("Craigendoran", "CGD");
  STATION("Cramlington", "CRM");
  STATION("Cranbrook (Devon)", "CBK");
  STATION("Craven Arms", "CRV");
  STATION("Crawley", "CRW");
  STATION("Crayford", "CRY");
  STATION("Crediton", "CDI");
  STATION("Cressing (Essex)", "CES");
  STATION("Cressington", "CSG");
  STATION("Creswell", "CWD");
  STATION("Crewe", "CRE");
  STATION("Crewkerne", "CKN");
  STATION("Crews Hill", "CWH");
  STATION("Crianlarich", "CNR");
  STATION("Criccieth", "CCC");
  STATION("Cricklewood", "CRI");
  STATION("Croftfoot", "CFF");
  STATION("Crofton Park", "CFT");
  STATION("Cromer", "CMR");
  STATION("Cromford", "CMF");
  STATION("Crookston", "CKT");
  STATION("Cross Gates", "CRG");
  STATION("Crossflatts", "CFL");
  STATION("Crosshill", "COI");
  STATION("Crosskeys", "CKY");
  STATION("Crossmyloof", "CMY");
  STATION("Croston", "CSO");
  STATION("Crouch Hill", "CRH");
  STATION("Crowborough", "COH");
  STATION("Crowhurst", "CWU");
  STATION("Crowle", "CWE");
  STATION("Crowthorne", "CRN");
  STATION("Croy", "CRO");
  STATION("Crystal Palace", "CYP");
  STATION("Cuddington", "CUD");
  STATION("Cuffley", "CUF");
  STATION("Culham", "CUM");
  STATION("Culrain", "CUA");
  STATION("Cumbernauld", "CUB");
  STATION("Cupar", "CUP");
  STATION("Curriehill", "CUH");
  STATION("Cuxton", "CUX");
  STATION("Cwmbach", "CMH");
  STATION("Cwmbran", "CWM");
  STATION("Cynghordy", "CYN");
  STATION("Dagenham Dock", "DDK");
  STATION("Daisy Hill", "DSY");
  STATION("Dalgety Bay", "DAG");
  STATION("Dalmally", "DAL");
  STATION("Dalmarnock", "DAK");
  STATION("Dalmeny", "DAM");
  STATION("Dalmuir", "DMR");
  STATION("Dalreoch", "DLR");
  STATION("Dalry", "DLY");
  STATION("Dalston (Cumbria)", "DLS");
  STATION("Dalston Junction", "DLJ");
  STATION("Dalston Kingsland", "DLK");
  STATION("Dalton (Cumbria)", "DLT");
  STATION("Dalwhinnie", "DLW");
  STATION("Danby", "DNY");
  STATION("Danescourt", "DCT");
  STATION("Danzey", "DZY");
  STATION("Darlington", "DAR");
  STATION("Darnall", "DAN");
  STATION("Darsham", "DSM");
  STATION("Dartford", "DFD");
  STATION("Darton", "DRT");
  STATION("Darwen", "DWN");
  STATION("Datchet", "DAT");
  STATION("Davenport", "DVN");
  STATION("Dawlish Warren", "DWW");
  STATION("Dawlish", "DWL");
  STATION("Deal", "DEA");
  STATION("Dean (Wilts)", "DEN");
  STATION("Deansgate", "DGT");
  STATION("Deganwy", "DGY");
  STATION("Deighton", "DHN");
  STATION("Delamere", "DLM");
  STATION("Denby Dale", "DBD");
  STATION("Denham Golf Club", "DGC");
  STATION("Denham", "DNM");
  STATION("Denmark Hill", "DMK");
  STATION("Dent", "DNT");
  STATION("Denton", "DTN");
  STATION("Deptford", "DEP");
  STATION("Derby Road (Ipswich)", "DBR");
  STATION("Derby", "DBY");
  STATION("Devonport (Devon)", "DPT");
  STATION("Devonport Dockyard", "DOC");
  STATION("Dewsbury", "DEW");
  STATION("Didcot Parkway", "DID");
  STATION("Digby & Sowton", "DIG");
  STATION("Dilton Marsh", "DMH");
  STATION("Dinas (Rhondda)", "DMG");
  STATION("Dinas Powys", "DNS");
  STATION("Dingle Road", "DGL");
  STATION("Dingwall", "DIN");
  STATION("Dinsdale", "DND");
  STATION("Dinting", "DTG");
  STATION("Disley", "DSL");
  STATION("Diss", "DIS");
  STATION("Dodworth", "DOD");
  STATION("Dolau", "DOL");
  STATION("Doleham", "DLH");
  STATION("Dolgarrog", "DLG");
  STATION("Dolwyddelan", "DWD");
  STATION("Doncaster", "DON");
  STATION("Dorchester South", "DCH");
  STATION("Dorchester West", "DCW");
  STATION("Dore & Totley", "DOR");
  STATION("Dorking (Main)", "DKG");
  STATION("Dorking Deepdene", "DPD");
  STATION("Dorking West", "DKT");
  STATION("Dormans", "DMS");
  STATION("Dorridge", "DDG");
  STATION("Dove Holes", "DVH");
  STATION("Dover Priory", "DVP");
  STATION("Dovercourt", "DVC");
  STATION("Dovey Junction", "DVY");
  STATION("Downham Market", "DOW");
  STATION("Drayton Green", "DRG");
  STATION("Drayton Park", "DYP");
  STATION("Drem", "DRM");
  STATION("Driffield", "DRF");
  STATION("Drigg", "DRI");
  STATION("Droitwich Spa", "DTW");
  STATION("Dronfield", "DRO");
  STATION("Drumchapel", "DMC");
  STATION("Drumfrochar", "DFR");
  STATION("Drumgelloch", "DRU");
  STATION("Drumry", "DMY");
  STATION("Dublin Ferryport", "DFP");
  STATION("Dublin Port - Stena", "DPS");
  STATION("Duddeston", "DUD");
  STATION("Dudley Port", "DDP");
  STATION("Duffield", "DFI");
  STATION("Duirinish", "DRN");
  STATION("Duke Street", "DST");
  STATION("Dullingham", "DUL");
  STATION("Dumbarton Central", "DBC");
  STATION("Dumbarton East", "DBE");
  STATION("Dumbreck", "DUM");
  STATION("Dumfries", "DMF");
  STATION("Dumpton Park", "DMP");
  STATION("Dunbar", "DUN");
  STATION("Dunblane", "DBL");
  STATION("Duncraig", "DCG");
  STATION("Dundee", "DEE");
  STATION("Dunfermline Queen Margaret", "DFL");
  STATION("Dunfermline Town", "DFE");
  STATION("Dunkeld & Birnam", "DKD");
  STATION("Dunlop", "DNL");
  STATION("Dunrobin Castle", "DNO");
  STATION("Dunston", "DOT");
  STATION("Dunton Green", "DNG");
  STATION("Durham", "DHM");
  STATION("Durrington-on-Sea", "DUR");
  STATION("Dyce", "DYC");
  STATION("Dyffryn Ardudwy", "DYF");
  STATION("Eaglescliffe", "EAG");
  STATION("Ealing Broadway", "EAL");
  STATION("Earlestown", "ERL");
  STATION("Earley", "EAR");
  STATION("Earlsfield", "EAD");
  STATION("Earlswood (Surrey)", "ELD");
  STATION("Earlswood (West Midlands)", "EWD");
  STATION("East Croydon", "ECR");
  STATION("East Didsbury", "EDY");
  STATION("East Dulwich", "EDW");
  STATION("East Farleigh", "EFL");
  STATION("East Garforth", "EGF");
  STATION("East Grinstead", "EGR");
  STATION("East Kilbride", "EKL");
  STATION("East Malling", "EML");
  STATION("East Midlands Parkway", "EMD");
  STATION("East Tilbury", "ETL");
  STATION("East Worthing", "EWR");
  STATION("Eastbourne", "EBN");
  STATION("Eastbrook", "EBK");
  STATION("Easterhouse", "EST");
  STATION("Eastham Rake", "ERA");
  STATION("Eastleigh", "ESL");
  STATION("Eastrington", "EGN");
  STATION("Ebbsfleet International", "EBD");
  STATION("Ebbw Vale Parkway", "EBV");
  STATION("Ebbw Vale Town", "EBB");
  STATION("Eccles (Manchester)", "ECC");
  STATION("Eccles Road", "ECS");
  STATION("Eccleston Park", "ECL");
  STATION("Edale", "EDL");
  STATION("Eden Park", "EDN");
  STATION("Edenbridge Town", "EBT");
  STATION("Edenbridge", "EBR");
  STATION("Edge Hill", "EDG");
  STATION("Edinburgh Gateway", "EGY");
  STATION("Edinburgh Park", "EDP");
  STATION("Edinburgh", "EDB");
  STATION("Edmonton Green", "EDR");
  STATION("Effingham Junction", "EFF");
  STATION("Eggesford", "EGG");
  STATION("Egham", "EGH");
  STATION("Egton", "EGT");
  STATION("Elephant & Castle (Underground)", "ZEL");
  STATION("Elephant & Castle", "EPH");
  STATION("Elgin", "ELG");
  STATION("Ellesmere Port", "ELP");
  STATION("Elmers End", "ELE");
  STATION("Elmstead Woods", "ESD");
  STATION("Elmswell", "ESW");
  STATION("Elsecar", "ELR");
  STATION("Elsenham (Essex)", "ESM");
  STATION("Elstree & Borehamwood", "ELS");
  STATION("Eltham", "ELW");
  STATION("Elton & Orston", "ELO");
  STATION("Ely", "ELY");
  STATION("Emerson Park", "EMP");
  STATION("Emsworth", "EMS");
  STATION("Energlyn & Churchill Park", "ECP");
  STATION("Enfield Chase", "ENC");
  STATION("Enfield Lock", "ENL");
  STATION("Enfield Town", "ENF");
  STATION("Entwistle", "ENT");
  STATION("Epsom (Surrey)", "EPS");
  STATION("Epsom Downs", "EPD");
  STATION("Erdington", "ERD");
  STATION("Eridge", "ERI");
  STATION("Erith", "ERH");
  STATION("Esher", "ESH");
  STATION("Eskbank", "EKB");
  STATION("Essex Road", "EXR");
  STATION("Etchingham", "ETC");
  STATION("Euxton Balshaw Lane", "EBA");
  STATION("Evesham", "EVE");
  STATION("Ewell East", "EWE");
  STATION("Ewell West", "EWW");
  STATION("Exeter Central", "EXC");
  STATION("Exeter St David's", "EXD");
  STATION("Exeter St Thomas", "EXT");
  STATION("Exhibition Centre (Glasgow)", "EXG");
  STATION("Exmouth", "EXM");
  STATION("Exton", "EXN");
  STATION("Eynsford", "EYN");
  STATION("Fairbourne", "FRB");
  STATION("Fairfield", "FRF");
  STATION("Fairlie", "FRL");
  STATION("Fairwater", "FRW");
  STATION("Falconwood", "FCN");
  STATION("Falkirk Grahamston", "FKG");
  STATION("Falkirk High", "FKK");
  STATION("Falls of Cruachan", "FOC");
  STATION("Falmer", "FMR");
  STATION("Falmouth Docks", "FAL");
  STATION("Falmouth Town", "FMT");
  STATION("Fareham", "FRM");
  STATION("Farnborough (Main)", "FNB");
  STATION("Farnborough North", "FNN");
  STATION("Farncombe", "FNC");
  STATION("Farnham", "FNH");
  STATION("Farningham Road", "FNR");
  STATION("Farnworth", "FNW");
  STATION("Farringdon", "ZFD");
  STATION("Fauldhouse", "FLD");
  STATION("Faversham", "FAV");
  STATION("Faygate", "FGT");
  STATION("Fazakerley", "FAZ");
  STATION("Fearn", "FRN");
  STATION("Featherstone", "FEA");
  STATION("Felixstowe", "FLX");
  STATION("Feltham", "FEL");
  STATION("Feniton", "FNT");
  STATION("Fenny Stratford", "FEN");
  STATION("Fernhill", "FER");
  STATION("Ferriby", "FRY");
  STATION("Ferryside", "FYS");
  STATION("Ffairfach", "FFA");
  STATION("Filey", "FIL");
  STATION("Filton Abbey Wood", "FIT");
  STATION("Finchley Road & Frognal", "FNY");
  STATION("Finsbury Park", "FPK");
  STATION("Finstock", "FIN");
  STATION("Fishbourne (Sussex)", "FSB");
  STATION("Fishersgate", "FSG");
  STATION("Fishguard & Goodwick", "FGW");
  STATION("Fishguard Harbour", "FGH");
  STATION("Fiskerton", "FSK");
  STATION("Fitzwilliam", "FZW");
  STATION("Five Ways", "FWY");
  STATION("Fleet", "FLE");
  STATION("Flimby", "FLM");
  STATION("Flint", "FLN");
  STATION("Flitwick", "FLT");
  STATION("Flixton", "FLI");
  STATION("Flowery Field", "FLF");
  STATION("Folkestone Central", "FKC");
  STATION("Folkestone West", "FKW");
  STATION("Ford", "FOD");
  STATION("Forest Gate", "FOG");
  STATION("Forest Hill", "FOH");
  STATION("Formby", "FBY");
  STATION("Forres", "FOR");
  STATION("Forsinard", "FRS");
  STATION("Fort Matilda", "FTM");
  STATION("Fort William", "FTW");
  STATION("Four Oaks", "FOK");
  STATION("Foxfield", "FOX");
  STATION("Foxton", "FXN");
  STATION("Frant", "FRT");
  STATION("Fratton", "FTN");
  STATION("Freshfield", "FRE");
  STATION("Freshford", "FFD");
  STATION("Frimley", "FML");
  STATION("Frinton-on-Sea", "FRI");
  STATION("Frizinghall", "FZH");
  STATION("Frodsham", "FRD");
  STATION("Frome", "FRO");
  STATION("Fulwell", "FLW");
  STATION("Furness Vale", "FNV");
  STATION("Furze Platt", "FZP");
  STATION("Gainsborough Central", "GNB");
  STATION("Gainsborough Lea Road", "GBL");
  STATION("Galashiels", "GAL");
  STATION("Garelochhead", "GCH");
  STATION("Garforth", "GRF");
  STATION("Gargrave", "GGV");
  STATION("Garrowhill", "GAR");
  STATION("Garscadden", "GRS");
  STATION("Garsdale", "GSD");
  STATION("Garston (Hertfordshire)", "GSN");
  STATION("Garswood", "GSW");
  STATION("Gartcosh", "GRH");
  STATION("Garth (Mid Glamorgan)", "GMG");
  STATION("Garth (Powys)", "GTH");
  STATION("Garve", "GVE");
  STATION("Gathurst", "GST");
  STATION("Gatley", "GTY");
  STATION("Gatwick Airport", "GTW");
  STATION("Georgemas Junction", "GGJ");
  STATION("Gerrards Cross", "GER");
  STATION("Gidea Park", "GDP");
  STATION("Giffnock", "GFN");
  STATION("Giggleswick", "GIG");
  STATION("Gilberdyke", "GBD");
  STATION("Gilfach Fargoed", "GFF");
  STATION("Gillingham (Dorset)", "GIL");
  STATION("Gillingham (Kent)", "GLM");
  STATION("Gilshochill", "GSC");
  STATION("Gipsy Hill", "GIP");
  STATION("Girvan", "GIR");
  STATION("Glaisdale", "GLS");
  STATION("Glan Conwy", "GCW");
  STATION("Glasgow Central", "GLC");
  STATION("Glasgow Queen Street", "GLQ");
  STATION("Glasshoughton", "GLH");
  STATION("Glazebrook", "GLZ");
  STATION("Gleneagles", "GLE");
  STATION("Glenfinnan", "GLF");
  STATION("Glengarnock", "GLG");
  STATION("Glenrothes with Thornton", "GLT");
  STATION("Glossop", "GLO");
  STATION("Gloucester", "GCR");
  STATION("Glynde", "GLY");
  STATION("Gobowen", "GOB");
  STATION("Godalming", "GOD");
  STATION("Godley", "GDL");
  STATION("Godstone", "GDN");
  STATION("Goldthorpe", "GOE");
  STATION("Golf Street", "GOF");
  STATION("Golspie", "GOL");
  STATION("Gomshall", "GOM");
  STATION("Goodmayes", "GMY");
  STATION("Goole", "GOO");
  STATION("Goostrey", "GTR");
  STATION("Gordon Hill", "GDH");
  STATION("Gorebridge", "GBG");
  STATION("Goring & Streatley", "GOR");
  STATION("Goring-by-Sea", "GBS");
  STATION("Gorton", "GTO");
  STATION("Gospel Oak", "GPO");
  STATION("Gourock", "GRK");
  STATION("Gowerton", "GWN");
  STATION("Goxhill", "GOX");
  STATION("Grange Park", "GPK");
  STATION("Grange-Over-Sands", "GOS");
  STATION("Grangetown (Cardiff)", "GTN");
  STATION("Grantham", "GRA");
  STATION("Grateley", "GRT");
  STATION("Gravelly Hill", "GVH");
  STATION("Gravesend", "GRV");
  STATION("Grays", "GRY");
  STATION("Great Ayton", "GTA");
  STATION("Great Bentley", "GRB");
  STATION("Great Chesterford", "GRC");
  STATION("Great Coates", "GCT");
  STATION("Great Malvern", "GMV");
  STATION("Great Missenden", "GMN");
  STATION("Great Yarmouth", "GYM");
  STATION("Green Lane", "GNL");
  STATION("Green Road", "GNR");
  STATION("Greenbank", "GBK");
  STATION("Greenfaulds", "GRL");
  STATION("Greenfield", "GNF");
  STATION("Greenford", "GFD");
  STATION("Greenhithe", "GNH");
  STATION("Greenock Central", "GKC");
  STATION("Greenock West", "GKW");
  STATION("Greenwich", "GNW");
  STATION("Gretna Green", "GEA");
  STATION("Grimsby Docks", "GMD");
  STATION("Grimsby Town", "GMB");
  STATION("Grindleford", "GRN");
  STATION("Grosmont", "GMT");
  STATION("Grove Park", "GRP");
  STATION("Guide Bridge", "GUI");
  STATION("Guildford", "GLD");
  STATION("Guiseley", "GSY");
  STATION("Gunnersbury", "GUN");
  STATION("Gunnislake", "GSL");
  STATION("Gunton", "GNT");
  STATION("Gwersyllt", "GWE");
  STATION("Gypsy Lane", "GYP");
  STATION("Habrough", "HAB");
  STATION("Hackbridge", "HCB");
  STATION("Hackney Central", "HKC");
  STATION("Hackney Downs", "HAC");
  STATION("Hackney Wick", "HKW");
  STATION("Haddenham & Thame Parkway", "HDM");
  STATION("Haddiscoe", "HAD");
  STATION("Hadfield", "HDF");
  STATION("Hadley Wood", "HDW");
  STATION("Hag Fold", "HGF");
  STATION("Haggerston", "HGG");
  STATION("Hagley", "HAG");
  STATION("Hairmyres", "HMY");
  STATION("Hale (Manchester)", "HAL");
  STATION("Halesworth", "HAS");
  STATION("Halewood", "HED");
  STATION("Halifax", "HFX");
  STATION("Hall Green", "HLG");
  STATION("Hall Road", "HLR");
  STATION("Hall-i'-th'-Wood", "HID");
  STATION("Halling", "HAI");
  STATION("Haltwhistle", "HWH");
  STATION("Ham Street", "HMT");
  STATION("Hamble", "HME");
  STATION("Hamilton Central", "HNC");
  STATION("Hamilton West", "HNW");
  STATION("Hammerton", "HMM");
  STATION("Hampden Park (Sussex)", "HMD");
  STATION("Hampstead Heath", "HDH");
  STATION("Hampton (London)", "HMP");
  STATION("Hampton Court", "HMC");
  STATION("Hampton Wick", "HMW");
  STATION("Hampton-in-Arden", "HIA");
  STATION("Hamstead (Birmingham)", "HSD");
  STATION("Hamworthy", "HAM");
  STATION("Hanborough", "HND");
  STATION("Handforth", "HTH");
  STATION("Hanwell", "HAN");
  STATION("Hapton", "HPN");
  STATION("Harlech", "HRL");
  STATION("Harlesden", "HDN");
  STATION("Harling Road", "HRD");
  STATION("Harlington (Beds)", "HLN");
  STATION("Harlow Mill", "HWM");
  STATION("Harlow Town", "HWN");
  STATION("Harold Wood", "HRO");
  STATION("Harpenden", "HPD");
  STATION("Harrietsham", "HRM");
  STATION("Harringay Green Lanes", "HRY");
  STATION("Harringay", "HGY");
  STATION("Harrington", "HRR");
  STATION("Harrogate", "HGT");
  STATION("Harrow & Wealdstone", "HRW");
  STATION("Harrow-on-the-Hill", "HOH");
  STATION("Hartford (Cheshire)", "HTF");
  STATION("Hartlebury", "HBY");
  STATION("Hartlepool", "HPL");
  STATION("Hartwood", "HTW");
  STATION("Harwich International", "HPQ");
  STATION("Harwich Town", "HWC");
  STATION("Haslemere", "HSL");
  STATION("Hassocks", "HSK");
  STATION("Hastings", "HGS");
  STATION("Hatch End", "HTE");
  STATION("Hatfield & Stainforth", "HFS");
  STATION("Hatfield (Herts)", "HAT");
  STATION("Hatfield Peverel", "HAP");
  STATION("Hathersage", "HSG");
  STATION("Hattersley", "HTY");
  STATION("Hatton", "HTN");
  STATION("Havant", "HAV");
  STATION("Havenhouse", "HVN");
  STATION("Haverfordwest", "HVF");
  STATION("Hawarden Bridge", "HWB");
  STATION("Hawarden", "HWD");
  STATION("Hawkhead", "HKH");
  STATION("Haydon Bridge", "HDB");
  STATION("Haydons Road", "HYR");
  STATION("Hayes & Harlington", "HAY");
  STATION("Hayes (Kent)", "HYS");
  STATION("Hayle", "HYL");
  STATION("Haymarket", "HYM");
  STATION("Haywards Heath", "HHE");
  STATION("Hazel Grove", "HAZ");
  STATION("Headcorn", "HCN");
  STATION("Headingley", "HDY");
  STATION("Headstone Lane", "HDL");
  STATION("Heald Green", "HDG");
  STATION("Healing", "HLI");
  STATION("Heath High Level", "HHL");
  STATION("Heath Low Level", "HLL");
  STATION("Heathrow Airport Terminal 4", "HAF");
  STATION("Heathrow Airport Terminal 5", "HWV");
  STATION("Heathrow Airport", "HXX");
  STATION("Heaton Chapel", "HTC");
  STATION("Hebden Bridge", "HBD");
  STATION("Heckington", "HEC");
  STATION("Hedge End", "HDE");
  STATION("Hednesford", "HNF");
  STATION("Heighington", "HEI");
  STATION("Helensburgh Central", "HLC");
  STATION("Helensburgh Upper", "HLU");
  STATION("Hellifield", "HLD");
  STATION("Helmsdale", "HMS");
  STATION("Helsby", "HSB");
  STATION("Hemel Hempstead", "HML");
  STATION("Hendon", "HEN");
  STATION("Hengoed", "HNG");
  STATION("Henley-in-Arden", "HNL");
  STATION("Henley-on-Thames", "HOT");
  STATION("Hensall", "HEL");
  STATION("Hereford", "HFD");
  STATION("Herne Bay", "HNB");
  STATION("Herne Hill", "HNH");
  STATION("Hersham", "HER");
  STATION("Hertford East", "HFE");
  STATION("Hertford North", "HFN");
  STATION("Hessle", "HES");
  STATION("Heswall", "HSW");
  STATION("Hever", "HEV");
  STATION("Heworth", "HEW");
  STATION("Hexham", "HEX");
  STATION("Heyford", "HYD");
  STATION("Heysham Port", "HHB");
  STATION("High Brooms", "HIB");
  STATION("High Street (Glasgow)", "HST");
  STATION("High Street Kensington Underground", "ZHS");
  STATION("High Wycombe", "HWY");
  STATION("Higham (Kent)", "HGM");
  STATION("Highams Park", "HIP");
  STATION("Highbridge & Burnham", "HIG");
  STATION("Highbury & Islington", "HHY");
  STATION("Hightown", "HTO");
  STATION("Hildenborough", "HLB");
  STATION("Hillfoot", "HLF");
  STATION("Hillington East", "HLE");
  STATION("Hillington West", "HLW");
  STATION("Hillside", "HIL");
  STATION("Hilsea", "HLS");
  STATION("Hinchley Wood", "HYW");
  STATION("Hinckley (Leics)", "HNK");
  STATION("Hindley", "HIN");
  STATION("Hinton Admiral", "HNA");
  STATION("Hitchin", "HIT");
  STATION("Hither Green", "HGR");
  STATION("Hockley", "HOC");
  STATION("Hollingbourne", "HBN");
  STATION("Holmes Chapel", "HCH");
  STATION("Holmwood", "HLM");
  STATION("Holton Heath", "HOL");
  STATION("Holyhead", "HHD");
  STATION("Holytown", "HLY");
  STATION("Homerton", "HMN");
  STATION("Honeybourne", "HYB");
  STATION("Honiton", "HON");
  STATION("Honley", "HOY");
  STATION("Honor Oak Park", "HPA");
  STATION("Hook", "HOK");
  STATION("Hooton", "HOO");
  STATION("Hope (Derbyshire)", "HOP");
  STATION("Hope (Flintshire)", "HPE");
  STATION("Hopton Heath", "HPT");
  STATION("Horden", "HRE");
  STATION("Horley", "HOR");
  STATION("Hornbeam Park", "HBP");
  STATION("Hornsey", "HRN");
  STATION("Horsforth", "HRS");
  STATION("Horsham", "HRH");
  STATION("Horsley", "HSY");
  STATION("Horton-in-Ribblesdale", "HIR");
  STATION("Horwich Parkway", "HWI");
  STATION("Hoscar", "HSC");
  STATION("Hough Green", "HGN");
  STATION("Hounslow", "HOU");
  STATION("Hove", "HOV");
  STATION("Hoveton & Wroxham", "HXM");
  STATION("How Wood (Herts)", "HWW");
  STATION("Howden", "HOW");
  STATION("Howwood (Renfrewshire)", "HOZ");
  STATION("Hoxton", "HOX");
  STATION("Hoylake", "HYK");
  STATION("Hubberts Bridge", "HBB");
  STATION("Hucknall", "HKN");
  STATION("Huddersfield", "HUD");
  STATION("Hull", "HUL");
  STATION("Humphrey Park", "HUP");
  STATION("Huncoat", "HCT");
  STATION("Hungerford", "HGD");
  STATION("Hunmanby", "HUB");
  STATION("Huntingdon", "HUN");
  STATION("Huntly", "HNT");
  STATION("Hunts Cross", "HNX");
  STATION("Hurst Green", "HUR");
  STATION("Hutton Cranswick", "HUT");
  STATION("Huyton", "HUY");
  STATION("Hyde Central", "HYC");
  STATION("Hyde North", "HYT");
  STATION("Hykeham", "HKM");
  STATION("Hyndland", "HYN");
  STATION("Hythe (Essex)", "HYH");
  STATION("IBM Halt", "IBM");
  STATION("Ifield", "IFI");
  STATION("Ilford", "IFD");
  STATION("Ilkeston", "ILN");
  STATION("Ilkley", "ILK");
  STATION("Imperial Wharf", "IMW");
  STATION("Ince & Elton", "INE");
  STATION("Ince (Manchester)", "INC");
  STATION("Ingatestone", "INT");
  STATION("Insch", "INS");
  STATION("Invergordon", "IGD");
  STATION("Invergowrie", "ING");
  STATION("Inverkeithing", "INK");
  STATION("Inverkip", "INP");
  STATION("Inverness", "INV");
  STATION("Invershin", "INH");
  STATION("Inverurie", "INR");
  STATION("Ipswich", "IPS");
  STATION("Irlam", "IRL");
  STATION("Irvine", "IRV");
  STATION("Isleworth", "ISL");
  STATION("Islip", "ISP");
  STATION("Iver", "IVR");
  STATION("Ivybridge", "IVY");
  STATION("James Cook", "JCH");
  STATION("Jewellery Quarter", "JEQ");
  STATION("Johnston (Pembs)", "JOH");
  STATION("Johnstone (Strathclyde)", "JHN");
  STATION("Jordanhill", "JOR");
  STATION("Kearsley (Manchester)", "KSL");
  STATION("Kearsney (Kent)", "KSN");
  STATION("Keighley", "KEI");
  STATION("Keith", "KEH");
  STATION("Kelvedon", "KEL");
  STATION("Kelvindale", "KVD");
  STATION("Kemble", "KEM");
  STATION("Kempston Hardwick", "KMH");
  STATION("Kempton Park Racecourse", "KMP");
  STATION("Kemsing", "KMS");
  STATION("Kemsley", "KML");
  STATION("Kendal", "KEN");
  STATION("Kenilworth", "KNW");
  STATION("Kenley", "KLY");
  STATION("Kennett", "KNE");
  STATION("Kennishead", "KNS");
  STATION("Kensal Green", "KNL");
  STATION("Kensal Rise", "KNR");
  STATION("Kensington Olympia", "KPA");
  STATION("Kent House", "KTH");
  STATION("Kentish Town West", "KTW");
  STATION("Kentish Town", "KTN");
  STATION("Kenton", "KNT");
  STATION("Kents Bank", "KBK");
  STATION("Kettering", "KET");
  STATION("Kew Bridge", "KWB");
  STATION("Kew Gardens", "KWG");
  STATION("Keyham", "KEY");
  STATION("Keynsham", "KYN");
  STATION("Kidbrooke", "KDB");
  STATION("Kidderminster", "KID");
  STATION("Kidsgrove", "KDG");
  STATION("Kidwelly", "KWL");
  STATION("Kilburn High Road", "KBN");
  STATION("Kildale", "KLD");
  STATION("Kildonan", "KIL");
  STATION("Kilgetty", "KGT");
  STATION("Kilmarnock", "KMK");
  STATION("Kilmaurs", "KLM");
  STATION("Kilpatrick", "KPT");
  STATION("Kilwinning", "KWN");
  STATION("Kinbrace", "KBC");
  STATION("Kingham", "KGM");
  STATION("Kinghorn", "KGH");
  STATION("Kings Langley", "KGL");
  STATION("Kings Lynn", "KLN");
  STATION("Kings Norton", "KNN");
  STATION("Kings Nympton", "KGN");
  STATION("Kings Park", "KGP");
  STATION("Kings Sutton", "KGS");
  STATION("Kingsknowe", "KGE");
  STATION("Kingston", "KNG");
  STATION("Kingswood", "KND");
  STATION("Kingussie", "KIN");
  STATION("Kintbury", "KIT");
  STATION("Kirby Cross", "KBX");
  STATION("Kirk Sandall", "KKS");
  STATION("Kirkby (Merseyside)", "KIR");
  STATION("Kirkby Stephen", "KSW");
  STATION("Kirkby-in-Ashfield", "KKB");
  STATION("Kirkby-in-Furness", "KBF");
  STATION("Kirkcaldy", "KDY");
  STATION("Kirkconnel", "KRK");
  STATION("Kirkdale", "KKD");
  STATION("Kirkham & Wesham", "KKM");
  STATION("Kirkhill", "KKH");
  STATION("Kirknewton", "KKN");
  STATION("Kirkstall Forge", "KLF");
  STATION("Kirkwood", "KWD");
  STATION("Kirton Lindsey", "KTL");
  STATION("Kiveton Bridge", "KIV");
  STATION("Kiveton Park", "KVP");
  STATION("Knaresborough", "KNA");
  STATION("Knebworth", "KBW");
  STATION("Knighton", "KNI");
  STATION("Knockholt", "KCK");
  STATION("Knottingley", "KNO");
  STATION("Knucklas", "KNU");
  STATION("Knutsford", "KNF");
  STATION("Kyle of Lochalsh", "KYL");
  STATION("Ladybank", "LDY");
  STATION("Ladywell", "LAD");
  STATION("Laindon", "LAI");
  STATION("Lairg", "LRG");
  STATION("Lake", "LKE");
  STATION("Lakenheath", "LAK");
  STATION("Lamphey", "LAM");
  STATION("Lanark", "LNK");
  STATION("Lancaster", "LAN");
  STATION("Lancing", "LAC");
  STATION("Landywood", "LAW");
  STATION("Langbank", "LGB");
  STATION("Langho", "LHO");
  STATION("Langley (Berks)", "LNY");
  STATION("Langley Green", "LGG");
  STATION("Langley Mill", "LGM");
  STATION("Langside", "LGS");
  STATION("Langwathby", "LGW");
  STATION("Langwith-Whaley Thorns", "LAG");
  STATION("Lapford", "LAP");
  STATION("Lapworth", "LPW");
  STATION("Larbert", "LBT");
  STATION("Largs", "LAR");
  STATION("Larkhall", "LRH");
  STATION("Laurencekirk", "LAU");
  STATION("Lawrence Hill", "LWH");
  STATION("Layton (Lancs)", "LAY");
  STATION("Lazonby & Kirkoswald", "LZB");
  STATION("Lea Bridge", "LEB");
  STATION("Lea Green", "LEG");
  STATION("Lea Hall", "LEH");
  STATION("Leagrave", "LEA");
  STATION("Lealholm", "LHM");
  STATION("Leamington Spa", "LMS");
  STATION("Leasowe", "LSW");
  STATION("Leatherhead", "LHD");
  STATION("Ledbury", "LED");
  STATION("Lee (London)", "LEE");
  STATION("Leeds", "LDS");
  STATION("Leicester", "LEI");
  STATION("Leigh (Kent)", "LIH");
  STATION("Leigh-on-Sea", "LES");
  STATION("Leighton Buzzard", "LBZ");
  STATION("Lelant Saltings", "LTS");
  STATION("Lelant", "LEL");
  STATION("Lenham", "LEN");
  STATION("Lenzie", "LNZ");
  STATION("Leominster", "LEO");
  STATION("Letchworth Garden City", "LET");
  STATION("Leuchars (for St. Andrews)", "LEU");
  STATION("Levenshulme", "LVM");
  STATION("Lewes", "LWS");
  STATION("Lewisham", "LEW");
  STATION("Leyland", "LEY");
  STATION("Leyton Midland Road", "LEM");
  STATION("Leytonstone High Road", "LER");
  STATION("Lichfield City", "LIC");
  STATION("Lichfield Trent Valley", "LTV");
  STATION("Lidlington", "LID");
  STATION("Limehouse", "LHS");
  STATION("Lincoln Central", "LCN");
  STATION("Lingfield", "LFD");
  STATION("Lingwood", "LGD");
  STATION("Linlithgow", "LIN");
  STATION("Liphook", "LIP");
  STATION("Liskeard", "LSK");
  STATION("Liss", "LIS");
  STATION("Lisvane & Thornhill", "LVT");
  STATION("Little Kimble", "LTK");
  STATION("Little Sutton", "LTT");
  STATION("Littleborough", "LTL");
  STATION("Littlehampton", "LIT");
  STATION("Littlehaven", "LVN");
  STATION("Littleport", "LTP");
  STATION("Liverpool Central", "LVC");
  STATION("Liverpool James Street", "LVJ");
  STATION("Liverpool Lime Street", "LIV");
  STATION("Liverpool South Parkway", "LPY");
  STATION("Livingston North", "LSN");
  STATION("Livingston South", "LVG");
  STATION("Llanaber", "LLA");
  STATION("Llanbedr", "LBR");
  STATION("Llanbister Road", "LLT");
  STATION("Llanbradach", "LNB");
  STATION("Llandaf", "LLN");
  STATION("Llandanwg", "LDN");
  STATION("Llandecwyn", "LLC");
  STATION("Llandeilo", "LLL");
  STATION("Llandovery", "LLV");
  STATION("Llandrindod", "LLO");
  STATION("Llandudno Junction", "LLJ");
  STATION("Llandudno", "LLD");
  STATION("Llandybie", "LLI");
  STATION("Llanelli", "LLE");
  STATION("Llanfairfechan", "LLF");
  STATION("Llanfairpwll", "LPG");
  STATION("Llangadog", "LLG");
  STATION("Llangammarch", "LLM");
  STATION("Llangennech", "LLH");
  STATION("Llangynllo", "LGO");
  STATION("Llanharan", "LLR");
  STATION("Llanhilleth", "LTH");
  STATION("Llanishen", "LLS");
  STATION("Llanrwst", "LWR");
  STATION("Llansamlet", "LAS");
  STATION("Llantwit Major", "LWM");
  STATION("Llanwrda", "LNR");
  STATION("Llanwrtyd", "LNW");
  STATION("Llwyngwril", "LLW");
  STATION("Llwynypia", "LLY");
  STATION("Loch Awe", "LHA");
  STATION("Loch Eil Outward Bound", "LHE");
  STATION("Lochailort", "LCL");
  STATION("Locheilside", "LCS");
  STATION("Lochgelly", "LCG");
  STATION("Lochluichart", "LCC");
  STATION("Lochwinnoch", "LHW");
  STATION("Lockerbie", "LOC");
  STATION("Lockwood", "LCK");
  STATION("London Blackfriars", "BFR");
  STATION("London Bridge", "LBG");
  STATION("London Cannon Street", "CST");
  STATION("London Charing Cross", "CHX");
  STATION("London Euston", "EUS");
  STATION("London Fenchurch Street", "FST");
  STATION("London Fields", "LOF");
  STATION("London Kings Cross", "KGX");
  STATION("London Liverpool Street", "LST");
  STATION("London Marylebone", "MYB");
  STATION("London Paddington", "PAD");
  STATION("London Road (Brighton)", "LRB");
  STATION("London Road (Guildford)", "LRD");
  STATION("London St Pancras (Intl)", "SPX");
  STATION("London St Pancras International", "STP");
  STATION("London Victoria", "VIC");
  STATION("London Waterloo East", "WAE");
  STATION("London Waterloo", "WAT");
  STATION("Long Buckby", "LBK");
  STATION("Long Eaton", "LGE");
  STATION("Long Preston", "LPR");
  STATION("Longbeck", "LGK");
  STATION("Longbridge", "LOB");
  STATION("Longcross", "LNG");
  STATION("Longfield", "LGF");
  STATION("Longniddry", "LND");
  STATION("Longport", "LPT");
  STATION("Longton", "LGN");
  STATION("Looe", "LOO");
  STATION("Lostock Gralam", "LTG");
  STATION("Lostock Hall", "LOH");
  STATION("Lostock", "LOT");
  STATION("Lostwithiel", "LOS");
  STATION("Loughborough Junction", "LGJ");
  STATION("Loughborough", "LBO");
  STATION("Low Moor", "LMR");
  STATION("Lowdham", "LOW");
  STATION("Lower Sydenham", "LSY");
  STATION("Lowestoft", "LWT");
  STATION("Ludlow", "LUD");
  STATION("Luton Airport Parkway", "LTN");
  STATION("Luton", "LUT");
  STATION("Luxulyan", "LUX");
  STATION("Lydney", "LYD");
  STATION("Lye (West Midlands)", "LYE");
  STATION("Lymington Pier", "LYP");
  STATION("Lymington Town", "LYT");
  STATION("Lympstone Commando", "LYC");
  STATION("Lympstone Village", "LYM");
  STATION("Lytham", "LTM");
  STATION("Macclesfield", "MAC");
  STATION("Machynlleth", "MCN");
  STATION("Maesteg (Ewenny Road)", "MEW");
  STATION("Maesteg", "MST");
  STATION("Maghull North", "MNS");
  STATION("Maghull", "MAG");
  STATION("Maiden Newton", "MDN");
  STATION("Maidenhead", "MAI");
  STATION("Maidstone Barracks", "MDB");
  STATION("Maidstone East", "MDE");
  STATION("Maidstone West", "MDW");
  STATION("Malden Manor", "MAL");
  STATION("Mallaig", "MLG");
  STATION("Malton", "MLT");
  STATION("Malvern Link", "MVL");
  STATION("Manchester Airport", "MIA");
  STATION("Manchester Oxford Road", "MCO");
  STATION("Manchester Piccadilly", "MAN");
  STATION("Manchester United Football Ground", "MUF");
  STATION("Manchester Victoria", "MCV");
  STATION("Manea", "MNE");
  STATION("Manningtree", "MNG");
  STATION("Manor Park", "MNP");
  STATION("Manor Road", "MNR");
  STATION("Manorbier", "MRB");
  STATION("Manors", "MAS");
  STATION("Mansfield Woodhouse", "MSW");
  STATION("Mansfield", "MFT");
  STATION("March", "MCH");
  STATION("Marden (Kent)", "MRN");
  STATION("Margate", "MAR");
  STATION("Market Harborough", "MHR");
  STATION("Market Rasen", "MKR");
  STATION("Markinch", "MNC");
  STATION("Marks Tey", "MKT");
  STATION("Marlow", "MLW");
  STATION("Marple", "MPL");
  STATION("Marsden (Yorks)", "MSN");
  STATION("Marske", "MSK");
  STATION("Marston Green", "MGN");
  STATION("Martin Mill", "MTM");
  STATION("Martins Heron", "MAO");
  STATION("Marton", "MTO");
  STATION("Maryhill", "MYH");
  STATION("Maryland", "MYL");
  STATION("Maryport", "MRY");
  STATION("Matlock Bath", "MTB");
  STATION("Matlock", "MAT");
  STATION("Mauldeth Road", "MAU");
  STATION("Maxwell Park", "MAX");
  STATION("Maybole", "MAY");
  STATION("Maze Hill", "MZH");
  STATION("Meadowhall", "MHS");
  STATION("Meldreth", "MEL");
  STATION("Melksham", "MKM");
  STATION("Melton (Suffolk)", "MES");
  STATION("Melton Mowbray", "MMO");
  STATION("Menheniot", "MEN");
  STATION("Menston", "MNN");
  STATION("Meols Cop", "MEC");
  STATION("Meols", "MEO");
  STATION("Meopham", "MEP");
  STATION("Meridian Water", "MRW");
  STATION("Merryton", "MEY");
  STATION("Merstham", "MHM");
  STATION("Merthyr Tydfil", "MER");
  STATION("Merthyr Vale", "MEV");
  STATION("Metheringham", "MGM");
  STATION("MetroCentre", "MCE");
  STATION("Mexborough", "MEX");
  STATION("Micheldever", "MIC");
  STATION("Micklefield", "MIK");
  STATION("Middlesbrough", "MBR");
  STATION("Middlewood", "MDL");
  STATION("Midgham", "MDG");
  STATION("Milford (Surrey)", "MLF");
  STATION("Milford Haven", "MFH");
  STATION("Mill Hill (Lancs)", "MLH");
  STATION("Mill Hill Broadway", "MIL");
  STATION("Millbrook (Beds)", "MLB");
  STATION("Millbrook (Hants)", "MBK");
  STATION("Milliken Park", "MIN");
  STATION("Millom", "MLM");
  STATION("Mills Hill (Manchester)", "MIH");
  STATION("Milngavie", "MLN");
  STATION("Milton Keynes Central", "MKC");
  STATION("Minffordd", "MFF");
  STATION("Minster", "MSR");
  STATION("Mirfield", "MIR");
  STATION("Mistley", "MIS");
  STATION("Mitcham Eastfields", "MTC");
  STATION("Mitcham Junction", "MIJ");
  STATION("Mobberley", "MOB");
  STATION("Monifieth", "MON");
  STATION("Monks Risborough", "MRS");
  STATION("Montpelier", "MTP");
  STATION("Montrose", "MTS");
  STATION("Moorfields", "MRF");
  STATION("Moorgate", "MOG");
  STATION("Moorside", "MSD");
  STATION("Moorthorpe", "MRP");
  STATION("Morar", "MRR");
  STATION("Morchard Road", "MRD");
  STATION("Morden South", "MDS");
  STATION("Morecambe", "MCM");
  STATION("Moreton (Dorset)", "MTN");
  STATION("Moreton (Merseyside)", "MRT");
  STATION("Moreton-in-Marsh", "MIM");
  STATION("Morfa Mawddach", "MFA");
  STATION("Morley", "MLY");
  STATION("Morpeth", "MPT");
  STATION("Mortimer", "MOR");
  STATION("Mortlake", "MTL");
  STATION("Moses Gate", "MSS");
  STATION("Moss Side", "MOS");
  STATION("Mossley (Manchester)", "MSL");
  STATION("Mossley Hill", "MSH");
  STATION("Mosspark", "MPK");
  STATION("Moston", "MSO");
  STATION("Motherwell", "MTH");
  STATION("Motspur Park", "MOT");
  STATION("Mottingham", "MTG");
  STATION("Mottisfont & Dunbridge", "DBG");
  STATION("Mouldsworth", "MLD");
  STATION("Moulsecoomb", "MCB");
  STATION("Mount Florida", "MFL");
  STATION("Mount Vernon", "MTV");
  STATION("Mountain Ash", "MTA");
  STATION("Muir of Ord", "MOO");
  STATION("Muirend", "MUI");
  STATION("Musselburgh", "MUB");
  STATION("Mytholmroyd", "MYT");
  STATION("Nafferton", "NFN");
  STATION("Nailsea & Backwell", "NLS");
  STATION("Nairn", "NRN");
  STATION("Nantwich", "NAN");
  STATION("Narberth", "NAR");
  STATION("Narborough", "NBR");
  STATION("Navigation Road", "NVR");
  STATION("Neath", "NTH");
  STATION("Needham Market", "NMT");
  STATION("Neilston", "NEI");
  STATION("Nelson", "NEL");
  STATION("Neston", "NES");
  STATION("Netherfield", "NET");
  STATION("Nethertown", "NRT");
  STATION("Netley", "NTL");
  STATION("New Barnet", "NBA");
  STATION("New Beckenham", "NBC");
  STATION("New Brighton", "NBN");
  STATION("New Clee", "NCE");
  STATION("New Cross Gate", "NXG");
  STATION("New Cross", "NWX");
  STATION("New Cumnock", "NCK");
  STATION("New Eltham", "NEH");
  STATION("New Holland", "NHL");
  STATION("New Hythe", "NHE");
  STATION("New Lane", "NLN");
  STATION("New Malden", "NEM");
  STATION("New Mills Central", "NMC");
  STATION("New Mills Newtown", "NMN");
  STATION("New Milton", "NWM");
  STATION("New Pudsey", "NPD");
  STATION("New Southgate", "NSG");
  STATION("Newark Castle", "NCT");
  STATION("Newark North Gate", "NNG");
  STATION("Newbridge", "NBE");
  STATION("Newbury Racecourse", "NRC");
  STATION("Newbury", "NBY");
  STATION("Newcastle", "NCL");
  STATION("Newcourt", "NCO");
  STATION("Newcraighall", "NEW");
  STATION("Newhaven Harbour", "NVH");
  STATION("Newhaven Town", "NVN");
  STATION("Newington", "NGT");
  STATION("Newmarket", "NMK");
  STATION("Newport (Essex)", "NWE");
  STATION("Newport (South Wales)", "NWP");
  STATION("Newquay", "NQY");
  STATION("Newstead", "NSD");
  STATION("Newton (Lanark)", "NTN");
  STATION("Newton Abbot", "NTA");
  STATION("Newton Aycliffe", "NAY");
  STATION("Newton St Cyres", "NTC");
  STATION("Newton for Hyde", "NWN");
  STATION("Newton-le-Willows", "NLW");
  STATION("Newton-on-Ayr", "NOA");
  STATION("Newtongrange", "NEG");
  STATION("Newtonmore", "NWR");
  STATION("Newtown (Powys)", "NWT");
  STATION("Ninian Park", "NNP");
  STATION("Nitshill", "NIT");
  STATION("Norbiton", "NBT");
  STATION("Norbury", "NRB");
  STATION("Normans Bay", "NSB");
  STATION("Normanton", "NOR");
  STATION("North Berwick", "NBW");
  STATION("North Camp", "NCM");
  STATION("North Dulwich", "NDL");
  STATION("North Fambridge", "NFA");
  STATION("North Llanrwst", "NLR");
  STATION("North Queensferry", "NQU");
  STATION("North Road (Darlington)", "NRD");
  STATION("North Sheen", "NSH");
  STATION("North Walsham", "NWA");
  STATION("North Wembley", "NWB");
  STATION("Northallerton", "NTR");
  STATION("Northampton", "NMP");
  STATION("Northfield", "NFD");
  STATION("Northfleet", "NFL");
  STATION("Northolt Park", "NLT");
  STATION("Northumberland Park", "NUM");
  STATION("Northwich", "NWI");
  STATION("Norwich", "NRW");
  STATION("Norwood Junction", "NWD");
  STATION("Nottingham", "NOT");
  STATION("Nuneaton", "NUN");
  STATION("Nunhead", "NHD");
  STATION("Nunthorpe", "NNT");
  STATION("Nutbourne", "NUT");
  STATION("Nutfield", "NUF");
  STATION("Oakengates", "OKN");
  STATION("Oakham", "OKM");
  STATION("Oakleigh Park", "OKL");
  STATION("Oban", "OBN");
  STATION("Ockendon", "OCK");
  STATION("Ockley", "OLY");
  STATION("Okehampton", "OKE");
  STATION("Okehampton", "OKE");
  STATION("Old Hill", "OHL");
  STATION("Old Roan", "ORN");
  STATION("Old Street", "OLD");
  STATION("Oldfield Park", "OLF");
  STATION("Olton", "OLT");
  STATION("Ore", "ORE");
  STATION("Ormskirk", "OMS");
  STATION("Orpington", "ORP");
  STATION("Orrell Park", "OPK");
  STATION("Orrell", "ORR");
  STATION("Otford", "OTF");
  STATION("Oulton Broad North", "OUN");
  STATION("Oulton Broad South", "OUS");
  STATION("Outwood", "OUT");
  STATION("Overpool", "OVE");
  STATION("Overton", "OVR");
  STATION("Oxenholme Lake District", "OXN");
  STATION("Oxford Parkway", "OXP");
  STATION("Oxford", "OXF");
  STATION("Oxshott", "OXS");
  STATION("Oxted", "OXT");
  STATION("Paddock Wood", "PDW");
  STATION("Padgate", "PDG");
  STATION("Paignton", "PGN");
  STATION("Paisley Canal", "PCN");
  STATION("Paisley Gilmour Street", "PYG");
  STATION("Paisley St James", "PYJ");
  STATION("Palmers Green", "PAL");
  STATION("Pangbourne", "PAN");
  STATION("Pannal", "PNL");
  STATION("Pantyffynnon", "PTF");
  STATION("Par", "PAR");
  STATION("Parbold", "PBL");
  STATION("Park Street", "PKT");
  STATION("Parkstone (Dorset)", "PKS");
  STATION("Parson Street", "PSN");
  STATION("Partick", "PTK");
  STATION("Parton", "PRN");
  STATION("Patchway", "PWY");
  STATION("Patricroft", "PAT");
  STATION("Patterton", "PTT");
  STATION("Peartree", "PEA");
  STATION("Peckham Rye", "PMR");
  STATION("Pegswood", "PEG");
  STATION("Pemberton", "PEM");
  STATION("Pembrey & Burry Port", "PBY");
  STATION("Pembroke Dock", "PMD");
  STATION("Pembroke", "PMB");
  STATION("Pen-y-Bont", "PNY");
  STATION("Penally", "PNA");
  STATION("Penarth", "PEN");
  STATION("Pencoed", "PCD");
  STATION("Pengam", "PGM");
  STATION("Penge East", "PNE");
  STATION("Penge West", "PNW");
  STATION("Penhelig", "PHG");
  STATION("Penistone", "PNS");
  STATION("Penkridge", "PKG");
  STATION("Penmaenmawr", "PMW");
  STATION("Penmere", "PNM");
  STATION("Penrhiwceiber", "PER");
  STATION("Penrhyndeudraeth", "PRH");
  STATION("Penrith (North Lakes)", "PNR");
  STATION("Penryn (Cornwall)", "PYN");
  STATION("Pensarn (Gwynedd)", "PES");
  STATION("Penshurst", "PHR");
  STATION("Pentre-Bach", "PTB");
  STATION("Penychain", "PNC");
  STATION("Penyffordd", "PNF");
  STATION("Penzance", "PNZ");
  STATION("Perranwell", "PRW");
  STATION("Perry Barr", "PRY");
  STATION("Pershore", "PSH");
  STATION("Perth", "PTH");
  STATION("Peterborough", "PBO");
  STATION("Petersfield", "PTR");
  STATION("Petts Wood", "PET");
  STATION("Pevensey & Westham", "PEV");
  STATION("Pevensey Bay", "PEB");
  STATION("Pewsey", "PEW");
  STATION("Pilning", "PIL");
  STATION("Pinhoe", "PIN");
  STATION("Pitlochry", "PIT");
  STATION("Pitsea", "PSE");
  STATION("Pleasington", "PLS");
  STATION("Plockton", "PLK");
  STATION("Pluckley", "PLC");
  STATION("Plumley", "PLM");
  STATION("Plumpton", "PMP");
  STATION("Plumstead", "PLU");
  STATION("Plymouth", "PLY");
  STATION("Pokesdown", "POK");
  STATION("Polegate", "PLG");
  STATION("Polesworth", "PSW");
  STATION("Pollokshaws East", "PWE");
  STATION("Pollokshaws West", "PWW");
  STATION("Pollokshields East", "PLE");
  STATION("Pollokshields West", "PLW");
  STATION("Polmont", "PMT");
  STATION("Polsloe Bridge", "POL");
  STATION("Ponders End", "PON");
  STATION("Pont-y-Pant", "PYP");
  STATION("Pontarddulais", "PTD");
  STATION("Pontefract Baghill", "PFR");
  STATION("Pontefract Monkhill", "PFM");
  STATION("Pontefract Tanshelf", "POT");
  STATION("Pontlottyn", "PLT");
  STATION("Pontyclun", "PYC");
  STATION("Pontypool & New Inn", "PPL");
  STATION("Pontypridd", "PPD");
  STATION("Poole", "POO");
  STATION("Poppleton", "POP");
  STATION("Port Glasgow", "PTG");
  STATION("Port Sunlight", "PSL");
  STATION("Port Talbot Parkway", "PTA");
  STATION("Portchester", "PTC");
  STATION("Porth", "POR");
  STATION("Porthmadog", "PTM");
  STATION("Portlethen", "PLN");
  STATION("Portslade", "PLD");
  STATION("Portsmouth & Southsea", "PMS");
  STATION("Portsmouth Arms", "PMA");
  STATION("Portsmouth Harbour", "PMH");
  STATION("Possilpark & Parkhouse", "PPK");
  STATION("Potters Bar", "PBR");
  STATION("Poulton-le-Fylde", "PFY");
  STATION("Poynton", "PYT");
  STATION("Prees", "PRS");
  STATION("Prescot", "PSC");
  STATION("Prestatyn", "PRT");
  STATION("Prestbury", "PRB");
  STATION("Preston (Lancs)", "PRE");
  STATION("Preston Park", "PRP");
  STATION("Prestonpans", "PST");
  STATION("Prestwick International Airport", "PRA");
  STATION("Prestwick Town", "PTW");
  STATION("Priesthill & Darnley", "PTL");
  STATION("Princes Risborough", "PRR");
  STATION("Prittlewell", "PRL");
  STATION("Prudhoe", "PRU");
  STATION("Pulborough", "PUL");
  STATION("Purfleet", "PFL");
  STATION("Purley Oaks", "PUO");
  STATION("Purley", "PUR");
  STATION("Putney", "PUT");
  STATION("Pwllheli", "PWL");
  STATION("Pye Corner", "PYE");
  STATION("Pyle", "PYL");
  STATION("Quakers Yard", "QYD");
  STATION("Queenborough", "QBR");
  STATION("Queens Park (Glasgow)", "QPK");
  STATION("Queens Park (London)", "QPW");
  STATION("Queens Road (Peckham)", "QRP");
  STATION("Queenstown Road (Battersea)", "QRB");
  STATION("Quintrell Downs", "QUI");
  STATION("Radcliffe-on-Trent", "RDF");
  STATION("Radlett", "RDT");
  STATION("Radley", "RAD");
  STATION("Radyr", "RDR");
  STATION("Rainford", "RNF");
  STATION("Rainham (Essex)", "RNM");
  STATION("Rainham (Kent)", "RAI");
  STATION("Rainhill", "RNH");
  STATION("Ramsgate", "RAM");
  STATION("Ramsgreave & Wilpshire", "RGW");
  STATION("Rannoch", "RAN");
  STATION("Rauceby", "RAU");
  STATION("Ravenglass for Eskdale", "RAV");
  STATION("Ravensbourne", "RVB");
  STATION("Ravensthorpe", "RVN");
  STATION("Rawcliffe", "RWC");
  STATION("Rayleigh", "RLG");
  STATION("Raynes Park", "RAY");
  STATION("Reading West", "RDW");
  STATION("Reading", "RDG");
  STATION("Rectory Road", "REC");
  STATION("Redbridge", "RDB");
  STATION("Redcar British Steel", "RBS");
  STATION("Redcar Central", "RCC");
  STATION("Redcar East", "RCE");
  STATION("Reddish North", "RDN");
  STATION("Reddish South", "RDS");
  STATION("Redditch", "RDC");
  STATION("Redhill", "RDH");
  STATION("Redland", "RDA");
  STATION("Redruth", "RED");
  STATION("Reedham (Norfolk)", "REE");
  STATION("Reedham (Surrey)", "RHM");
  STATION("Reigate", "REI");
  STATION("Renton", "RTN");
  STATION("Retford", "RET");
  STATION("Rhiwbina", "RHI");
  STATION("Rhoose Cardiff International Airport", "RIA");
  STATION("Rhosneigr", "RHO");
  STATION("Rhyl", "RHL");
  STATION("Rhymney", "RHY");
  STATION("Ribblehead", "RHD");
  STATION("Rice Lane", "RIL");
  STATION("Richmond (London)", "RMD");
  STATION("Rickmansworth", "RIC");
  STATION("Riddlesdown", "RDD");
  STATION("Ridgmont", "RID");
  STATION("Riding Mill", "RDM");
  STATION("Risca & Pontymister", "RCA");
  STATION("Rishton", "RIS");
  STATION("Robertsbridge", "RBR");
  STATION("Robroyston", "RRN");
  STATION("Roby", "ROB");
  STATION("Rochdale", "RCD");
  STATION("Roche", "ROC");
  STATION("Rochester", "RTR");
  STATION("Rochford", "RFD");
  STATION("Rock Ferry", "RFY");
  STATION("Rogart", "ROG");
  STATION("Rogerstone", "ROR");
  STATION("Rolleston", "ROL");
  STATION("Roman Bridge", "RMB");
  STATION("Romford", "RMF");
  STATION("Romiley", "RML");
  STATION("Romsey", "ROM");
  STATION("Roose", "ROO");
  STATION("Rose Grove", "RSG");
  STATION("Rose Hill Marple", "RSH");
  STATION("Rosyth", "ROS");
  STATION("Rotherham Central", "RMC");
  STATION("Rotherhithe", "ROE");
  STATION("Roughton Road", "RNR");
  STATION("Rowlands Castle", "RLN");
  STATION("Rowley Regis", "ROW");
  STATION("Roy Bridge", "RYB");
  STATION("Roydon", "RYN");
  STATION("Royston", "RYS");
  STATION("Ruabon", "RUA");
  STATION("Rufford", "RUF");
  STATION("Rugby", "RUG");
  STATION("Rugeley Town", "RGT");
  STATION("Rugeley Trent Valley", "RGL");
  STATION("Runcorn East", "RUE");
  STATION("Runcorn", "RUN");
  STATION("Ruskington", "RKT");
  STATION("Ruswarp", "RUS");
  STATION("Rutherglen", "RUT");
  STATION("Ryde Esplanade", "RYD");
  STATION("Ryde Pier Head", "RYP");
  STATION("Ryde St Johns Road", "RYR");
  STATION("Ryder Brow", "RRB");
  STATION("Rye (Sussex)", "RYE");
  STATION("Rye House", "RYH");
  STATION("Salford Central", "SFD");
  STATION("Salford Crescent", "SLD");
  STATION("Salfords (Surrey)", "SAF");
  STATION("Salhouse", "SAH");
  STATION("Salisbury", "SAL");
  STATION("Saltaire", "SAE");
  STATION("Saltash", "STS");
  STATION("Saltburn", "SLB");
  STATION("Saltcoats", "SLT");
  STATION("Saltmarshe", "SAM");
  STATION("Salwick", "SLW");
  STATION("Sampford Courtenay", "SMC");
  STATION("Sandal & Agbrigg", "SNA");
  STATION("Sandbach", "SDB");
  STATION("Sanderstead", "SNR");
  STATION("Sandhills", "SDL");
  STATION("Sandhurst (Berks)", "SND");
  STATION("Sandling", "SDG");
  STATION("Sandown", "SAN");
  STATION("Sandplace", "SDP");
  STATION("Sandwell & Dudley", "SAD");
  STATION("Sandwich", "SDW");
  STATION("Sandy", "SDY");
  STATION("Sankey for Penketh", "SNK");
  STATION("Sanquhar", "SQH");
  STATION("Sarn", "SRR");
  STATION("Saundersfoot", "SDF");
  STATION("Saunderton", "SDR");
  STATION("Sawbridgeworth", "SAW");
  STATION("Saxilby", "SXY");
  STATION("Saxmundham", "SAX");
  STATION("Scarborough", "SCA");
  STATION("Scotscalder", "SCT");
  STATION("Scotstounhill", "SCH");
  STATION("Scunthorpe", "SCU");
  STATION("Sea Mills", "SML");
  STATION("Seaford (Sussex)", "SEF");
  STATION("Seaforth & Litherland", "SFL");
  STATION("Seaham", "SEA");
  STATION("Seamer", "SEM");
  STATION("Seascale", "SSC");
  STATION("Seaton Carew", "SEC");
  STATION("Seer Green & Jordans", "SRG");
  STATION("Selby", "SBY");
  STATION("Selhurst", "SRS");
  STATION("Sellafield", "SEL");
  STATION("Selling", "SEG");
  STATION("Selly Oak", "SLY");
  STATION("Settle", "SET");
  STATION("Seven Kings", "SVK");
  STATION("Seven Sisters", "SVS");
  STATION("Sevenoaks", "SEV");
  STATION("Severn Beach", "SVB");
  STATION("Severn Tunnel Junction", "STJ");
  STATION("Shadwell", "SDE");
  STATION("Shalford (Surrey)", "SFR");
  STATION("Shanklin", "SHN");
  STATION("Shawfair", "SFI");
  STATION("Shawford", "SHW");
  STATION("Shawlands", "SHL");
  STATION("Sheerness-on-Sea", "SSS");
  STATION("Sheffield", "SHF");
  STATION("Shelford (Cambs)", "SED");
  STATION("Shenfield", "SNF");
  STATION("Shenstone", "SEN");
  STATION("Shepherd's Bush", "SPB");
  STATION("Shepherds Well", "SPH");
  STATION("Shepley", "SPY");
  STATION("Shepperton", "SHP");
  STATION("Shepreth", "STH");
  STATION("Sherborne", "SHE");
  STATION("Sherburn-in-Elmet", "SIE");
  STATION("Sheringham", "SHM");
  STATION("Shettleston", "SLS");
  STATION("Shieldmuir", "SDM");
  STATION("Shifnal", "SFN");
  STATION("Shildon", "SHD");
  STATION("Shiplake", "SHI");
  STATION("Shipley (Yorks)", "SHY");
  STATION("Shippea Hill", "SPP");
  STATION("Shipton", "SIP");
  STATION("Shirebrook", "SHB");
  STATION("Shirehampton", "SHH");
  STATION("Shireoaks", "SRO");
  STATION("Shirley", "SRL");
  STATION("Shoeburyness", "SRY");
  STATION("Sholing", "SHO");
  STATION("Shoreditch High Street", "SDC");
  STATION("Shoreham (Kent)", "SEH");
  STATION("Shoreham-by-Sea", "SSE");
  STATION("Shortlands", "SRT");
  STATION("Shotton", "SHT");
  STATION("Shotts", "SHS");
  STATION("Shrewsbury", "SHR");
  STATION("Sidcup", "SID");
  STATION("Sileby", "SIL");
  STATION("Silecroft", "SIC");
  STATION("Silkstone Common", "SLK");
  STATION("Silver Street", "SLV");
  STATION("Silverdale", "SVR");
  STATION("Singer", "SIN");
  STATION("Sittingbourne", "SIT");
  STATION("Skegness", "SKG");
  STATION("Skewen", "SKE");
  STATION("Skipton", "SKI");
  STATION("Slade Green", "SGR");
  STATION("Slaithwaite", "SWT");
  STATION("Slateford", "SLA");
  STATION("Sleaford", "SLR");
  STATION("Sleights", "SLH");
  STATION("Slough", "SLO");
  STATION("Small Heath", "SMA");
  STATION("Smallbrook Junction", "SAB");
  STATION("Smethwick Galton Bridge", "SGB");
  STATION("Smethwick Rolfe Street", "SMR");
  STATION("Smithy Bridge", "SMB");
  STATION("Snaith", "SNI");
  STATION("Snodland", "SDA");
  STATION("Snowdown", "SWO");
  STATION("Sole Street", "SOR");
  STATION("Solihull", "SOL");
  STATION("Somerleyton", "SYT");
  STATION("South Acton", "SAT");
  STATION("South Bank", "SBK");
  STATION("South Bermondsey", "SBM");
  STATION("South Croydon", "SCY");
  STATION("South Elmsall", "SES");
  STATION("South Greenford", "SGN");
  STATION("South Gyle", "SGL");
  STATION("South Hampstead", "SOH");
  STATION("South Kenton", "SOK");
  STATION("South Merton", "SMO");
  STATION("South Milford", "SOM");
  STATION("South Ruislip", "SRU");
  STATION("South Tottenham", "STO");
  STATION("South Wigston", "SWS");
  STATION("South Woodham Ferrers", "SOF");
  STATION("Southall", "STL");
  STATION("Southampton Airport Parkway", "SOA");
  STATION("Southampton Central", "SOU");
  STATION("Southbourne", "SOB");
  STATION("Southbury", "SBU");
  STATION("Southease", "SEE");
  STATION("Southend Airport", "SIA");
  STATION("Southend Central", "SOC");
  STATION("Southend East", "SOE");
  STATION("Southend Victoria", "SOV");
  STATION("Southminster", "SMN");
  STATION("Southport", "SOP");
  STATION("Southwick", "SWK");
  STATION("Sowerby Bridge", "SOW");
  STATION("Spalding", "SPA");
  STATION("Spean Bridge", "SBR");
  STATION("Spital", "SPI");
  STATION("Spondon", "SPO");
  STATION("Spooner Row", "SPN");
  STATION("Spring Road", "SRI");
  STATION("Springburn", "SPR");
  STATION("Springfield", "SPF");
  STATION("Squires Gate", "SQU");
  STATION("St Albans Abbey", "SAA");
  STATION("St Albans City", "SAC");
  STATION("St Andrews Road", "SAR");
  STATION("St Annes-on-Sea", "SAS");
  STATION("St Austell", "SAU");
  STATION("St Bees", "SBS");
  STATION("St Budeaux Ferry Road", "SBF");
  STATION("St Budeaux Victoria Road", "SBV");
  STATION("St Columb Road", "SCR");
  STATION("St Denys", "SDN");
  STATION("St Erth", "SER");
  STATION("St Germans", "SGM");
  STATION("St Helens Central", "SNH");
  STATION("St Helens Junction", "SHJ");
  STATION("St Helier (Surrey)", "SIH");
  STATION("St Ives (Cornwall)", "SIV");
  STATION("St James Park (Exeter)", "SJP");
  STATION("St James Street (Walthamstow)", "SJS");
  STATION("St Johns (London)", "SAJ");
  STATION("St Keyne Wishing Well Halt", "SKN");
  STATION("St Leonards Warrior Square", "SLQ");
  STATION("St Margarets (Herts)", "SMT");
  STATION("St Margarets (London)", "SMG");
  STATION("St Mary Cray", "SMY");
  STATION("St Michaels", "STM");
  STATION("St Neots", "SNO");
  STATION("Stafford", "STA");
  STATION("Staines", "SNS");
  STATION("Stallingborough", "SLL");
  STATION("Stalybridge", "SYB");
  STATION("Stamford (Lincs)", "SMD");
  STATION("Stamford Hill", "SMH");
  STATION("Stanford-le-Hope", "SFO");
  STATION("Stanlow & Thornton", "SNT");
  STATION("Stansted Airport", "SSD");
  STATION("Stansted Mountfitchet", "SST");
  STATION("Staplehurst", "SPU");
  STATION("Stapleton Road", "SRD");
  STATION("Starbeck", "SBE");
  STATION("Starcross", "SCS");
  STATION("Staveley (Cumbria)", "SVL");
  STATION("Stechford", "SCF");
  STATION("Steeton & Silsden", "SON");
  STATION("Stepps", "SPS");
  STATION("Stevenage", "SVG");
  STATION("Stevenston", "STV");
  STATION("Stewartby", "SWR");
  STATION("Stewarton", "STT");
  STATION("Stirling", "STG");
  STATION("Stockport", "SPT");
  STATION("Stocksfield", "SKS");
  STATION("Stocksmoor", "SSM");
  STATION("Stockton", "STK");
  STATION("Stoke Mandeville", "SKM");
  STATION("Stoke Newington", "SKW");
  STATION("Stoke-on-Trent", "SOT");
  STATION("Stone (Staffs)", "SNE");
  STATION("Stone Crossing", "SCG");
  STATION("Stonebridge Park", "SBP");
  STATION("Stonegate", "SOG");
  STATION("Stonehaven", "STN");
  STATION("Stonehouse", "SHU");
  STATION("Stoneleigh", "SNL");
  STATION("Stourbridge Junction", "SBJ");
  STATION("Stourbridge Town", "SBT");
  STATION("Stow", "SOI");
  STATION("Stowmarket", "SMK");
  STATION("Stranraer", "STR");
  STATION("Stratford (London)", "SRA");
  STATION("Stratford International", "SFA");
  STATION("Stratford-upon-Avon Parkway", "STY");
  STATION("Stratford-upon-Avon", "SAV");
  STATION("Strathcarron", "STC");
  STATION("Strawberry Hill", "STW");
  STATION("Streatham (Greater London)", "STE");
  STATION("Streatham Common", "SRC");
  STATION("Streatham Hill", "SRH");
  STATION("Streethouse", "SHC");
  STATION("Strines", "SRN");
  STATION("Stromeferry", "STF");
  STATION("Strood (Kent)", "SOO");
  STATION("Stroud (Gloucs)", "STD");
  STATION("Sturry", "STU");
  STATION("Styal", "SYA");
  STATION("Sudbury & Harrow Road", "SUD");
  STATION("Sudbury (Suffolk)", "SUY");
  STATION("Sudbury Hill Harrow", "SDH");
  STATION("Sugar Loaf", "SUG");
  STATION("Summerston", "SUM");
  STATION("Sunbury", "SUU");
  STATION("Sunderland", "SUN");
  STATION("Sundridge Park", "SUP");
  STATION("Sunningdale", "SNG");
  STATION("Sunnymeads", "SNY");
  STATION("Surbiton", "SUR");
  STATION("Surrey Quays", "SQE");
  STATION("Sutton (Surrey)", "SUO");
  STATION("Sutton Coldfield", "SUT");
  STATION("Sutton Common", "SUC");
  STATION("Sutton Parkway", "SPK");
  STATION("Swale", "SWL");
  STATION("Swanley", "SAY");
  STATION("Swanscombe", "SWM");
  STATION("Swansea", "SWA");
  STATION("Swanwick", "SNW");
  STATION("Sway", "SWY");
  STATION("Swaythling", "SWG");
  STATION("Swinderby", "SWD");
  STATION("Swindon (Wilts)", "SWI");
  STATION("Swineshead", "SWE");
  STATION("Swinton (Manchester)", "SNN");
  STATION("Swinton (South Yorks)", "SWN");
  STATION("Sydenham (London)", "SYD");
  STATION("Sydenham Hill", "SYH");
  STATION("Syon Lane", "SYL");
  STATION("Syston", "SYS");
  STATION("Tackley", "TAC");
  STATION("Tadworth", "TAD");
  STATION("Taffs Well", "TAF");
  STATION("Tain", "TAI");
  STATION("Tal-y-Cafn", "TLC");
  STATION("Talsarnau", "TAL");
  STATION("Talybont", "TLB");
  STATION("Tame Bridge Parkway", "TAB");
  STATION("Tamworth", "TAM");
  STATION("Taplow", "TAP");
  STATION("Tattenham Corner", "TAT");
  STATION("Taunton", "TAU");
  STATION("Taynuilt", "TAY");
  STATION("Teddington", "TED");
  STATION("Tees-side Airport", "TEA");
  STATION("Teignmouth", "TGM");
  STATION("Telford Central", "TFC");
  STATION("Templecombe", "TMC");
  STATION("Tenby", "TEN");
  STATION("Teynham", "TEY");
  STATION("Thames Ditton", "THD");
  STATION("Thatcham", "THA");
  STATION("Thatto Heath", "THH");
  STATION("The Hawthorns", "THW");
  STATION("The Lakes (Warks)", "TLK");
  STATION("Theale", "THE");
  STATION("Theobalds Grove", "TEO");
  STATION("Thetford", "TTF");
  STATION("Thirsk", "THI");
  STATION("Thornaby", "TBY");
  STATION("Thorne North", "TNN");
  STATION("Thorne South", "TNS");
  STATION("Thornford", "THO");
  STATION("Thornliebank", "THB");
  STATION("Thornton Abbey", "TNA");
  STATION("Thornton Heath", "TTH");
  STATION("Thorntonhall", "THT");
  STATION("Thorpe Bay", "TPB");
  STATION("Thorpe Culvert", "TPC");
  STATION("Thorpe-le-Soken", "TLS");
  STATION("Three Bridges", "TBD");
  STATION("Three Oaks", "TOK");
  STATION("Thurgarton", "THU");
  STATION("Thurnscoe", "THC");
  STATION("Thurso", "THS");
  STATION("Thurston", "TRS");
  STATION("Tilbury Town", "TIL");
  STATION("Tile Hill", "THL");
  STATION("Tilehurst", "TLH");
  STATION("Tipton", "TIP");
  STATION("Tir-Phil", "TIR");
  STATION("Tisbury", "TIS");
  STATION("Tiverton Parkway", "TVP");
  STATION("Todmorden", "TOD");
  STATION("Tolworth", "TOL");
  STATION("Ton Pentre", "TPN");
  STATION("Tonbridge", "TON");
  STATION("Tondu", "TDU");
  STATION("Tonfanau", "TNF");
  STATION("Tonypandy", "TNP");
  STATION("Tooting", "TOO");
  STATION("Topsham", "TOP");
  STATION("Torquay", "TQY");
  STATION("Torre", "TRR");
  STATION("Totnes", "TOT");
  STATION("Tottenham Hale", "TOM");
  STATION("Totton", "TTN");
  STATION("Town Green", "TWN");
  STATION("Trafford Park", "TRA");
  STATION("Trefforest Estate", "TRE");
  STATION("Trefforest", "TRF");
  STATION("Trehafod", "TRH");
  STATION("Treherbert", "TRB");
  STATION("Treorchy", "TRY");
  STATION("Trimley", "TRM");
  STATION("Tring", "TRI");
  STATION("Troed-y-rhiw", "TRD");
  STATION("Troon", "TRN");
  STATION("Trowbridge", "TRO");
  STATION("Truro", "TRU");
  STATION("Tulloch", "TUL");
  STATION("Tulse Hill", "TUH");
  STATION("Tunbridge Wells", "TBW");
  STATION("Turkey Street", "TUR");
  STATION("Tutbury & Hatton", "TUT");
  STATION("Tweedbank", "TWB");
  STATION("Twickenham", "TWI");
  STATION("Twyford", "TWY");
  STATION("Ty Croes", "TYC");
  STATION("Ty Glas", "TGS");
  STATION("Tygwyn", "TYG");
  STATION("Tyndrum Lower", "TYL");
  STATION("Tyseley", "TYS");
  STATION("Tywyn", "TYW");
  STATION("Uckfield", "UCK");
  STATION("Uddingston", "UDD");
  STATION("Ulceby", "ULC");
  STATION("Ulleskelf", "ULL");
  STATION("Ulverston", "ULV");
  STATION("Umberleigh", "UMB");
  STATION("University (Birmingham)", "UNI");
  STATION("Uphall", "UHA");
  STATION("Upholland", "UPL");
  STATION("Upminster", "UPM");
  STATION("Upper Halliford", "UPH");
  STATION("Upper Holloway", "UHL");
  STATION("Upper Tyndrum", "UTY");
  STATION("Upper Warlingham", "UWL");
  STATION("Upton (Merseyside)", "UPT");
  STATION("Upwey", "UPW");
  STATION("Urmston", "URM");
  STATION("Uttoxeter", "UTT");
  STATION("Valley", "VAL");
  STATION("Vauxhall", "VXH");
  STATION("Virginia Water", "VIR");
  STATION("Waddon", "WDO");
  STATION("Wadhurst", "WAD");
  STATION("Wainfleet", "WFL");
  STATION("Wakefield Kirkgate", "WKK");
  STATION("Wakefield Westgate", "WKF");
  STATION("Walkden", "WKD");
  STATION("Wallasey Grove Road", "WLG");
  STATION("Wallasey Village", "WLV");
  STATION("Wallington", "WLT");
  STATION("Wallyford", "WAF");
  STATION("Walmer", "WAM");
  STATION("Walsall", "WSL");
  STATION("Walsden", "WDN");
  STATION("Waltham Cross", "WLC");
  STATION("Walthamstow Central", "WHC");
  STATION("Walthamstow Queen's Road", "WMW");
  STATION("Walton (Merseyside)", "WAO");
  STATION("Walton-on-Thames", "WAL");
  STATION("Walton-on-the-Naze", "WON");
  STATION("Wanborough", "WAN");
  STATION("Wandsworth Common", "WSW");
  STATION("Wandsworth Road", "WWR");
  STATION("Wandsworth Town", "WNT");
  STATION("Wanstead Park", "WNP");
  STATION("Wapping", "WPE");
  STATION("Warblington", "WBL");
  STATION("Ware (Herts)", "WAR");
  STATION("Wareham (Dorset)", "WRM");
  STATION("Wargrave", "WGV");
  STATION("Warminster", "WMN");
  STATION("Warnham", "WNH");
  STATION("Warrington Bank Quay", "WBQ");
  STATION("Warrington Central", "WAC");
  STATION("Warrington West", "WAW");
  STATION("Warwick Parkway", "WRP");
  STATION("Warwick", "WRW");
  STATION("Water Orton", "WTO");
  STATION("Waterbeach", "WBC");
  STATION("Wateringbury", "WTR");
  STATION("Waterloo (Merseyside)", "WLO");
  STATION("Watford High Street", "WFH");
  STATION("Watford Junction", "WFJ");
  STATION("Watford North", "WFN");
  STATION("Watlington", "WTG");
  STATION("Watton-at-Stone", "WAS");
  STATION("Waun-Gron Park", "WNG");
  STATION("Wavertree Technology Park", "WAV");
  STATION("Wedgwood", "WED");
  STATION("Weeley", "WEE");
  STATION("Weeton", "WET");
  STATION("Welham Green", "WMG");
  STATION("Welling", "WLI");
  STATION("Wellingborough", "WEL");
  STATION("Wellington (Shropshire)", "WLN");
  STATION("Welshpool", "WLP");
  STATION("Welwyn Garden City", "WGC");
  STATION("Welwyn North", "WLW");
  STATION("Wem", "WEM");
  STATION("Wembley Central", "WMB");
  STATION("Wembley Stadium", "WCX");
  STATION("Wemyss Bay", "WMS");
  STATION("Wendover", "WND");
  STATION("Wennington", "WNN");
  STATION("West Allerton", "WSA");
  STATION("West Brompton", "WBP");
  STATION("West Byfleet", "WBY");
  STATION("West Calder", "WCL");
  STATION("West Croydon", "WCY");
  STATION("West Drayton", "WDT");
  STATION("West Dulwich", "WDU");
  STATION("West Ealing", "WEA");
  STATION("West Ham", "WEH");
  STATION("West Hampstead Thameslink", "WHP");
  STATION("West Hampstead", "WHD");
  STATION("West Horndon", "WHR");
  STATION("West Kilbride", "WKB");
  STATION("West Kirby", "WKI");
  STATION("West Malling", "WMA");
  STATION("West Norwood", "WNW");
  STATION("West Ruislip", "WRU");
  STATION("West Runton", "WRN");
  STATION("West St Leonards", "WLD");
  STATION("West Sutton", "WSU");
  STATION("West Wickham", "WWI");
  STATION("West Worthing", "WWO");
  STATION("Westbury (Wilts)", "WSB");
  STATION("Westcliff", "WCF");
  STATION("Westcombe Park", "WCB");
  STATION("Westenhanger", "WHA");
  STATION("Wester Hailes", "WTA");
  STATION("Westerfield", "WFI");
  STATION("Westerton", "WES");
  STATION("Westgate-on-Sea", "WGA");
  STATION("Westhoughton", "WHG");
  STATION("Weston Milton", "WNM");
  STATION("Weston-super-Mare", "WSM");
  STATION("Wetheral", "WRL");
  STATION("Weybridge", "WYB");
  STATION("Weymouth", "WEY");
  STATION("Whaley Bridge", "WBR");
  STATION("Whalley (Lancs)", "WHE");
  STATION("Whatstandwell", "WTS");
  STATION("Whifflet", "WFF");
  STATION("Whimple", "WHM");
  STATION("Whinhill", "WNL");
  STATION("Whiston", "WHN");
  STATION("Whitby", "WTB");
  STATION("Whitchurch (Cardiff)", "WHT");
  STATION("Whitchurch (Hants)", "WCH");
  STATION("Whitchurch (Shropshire)", "WTC");
  STATION("White Hart Lane", "WHL");
  STATION("White Notley", "WNY");
  STATION("Whitechapel", "ZLW");
  STATION("Whitecraigs", "WCR");
  STATION("Whitehaven", "WTH");
  STATION("Whitland", "WTL");
  STATION("Whitley Bridge", "WBD");
  STATION("Whitlocks End", "WTE");
  STATION("Whitstable", "WHI");
  STATION("Whittlesea", "WLE");
  STATION("Whittlesford Parkway", "WLF");
  STATION("Whitton (London)", "WTN");
  STATION("Whitwell (Derbyshire)", "WWL");
  STATION("Whyteleafe South", "WHS");
  STATION("Whyteleafe", "WHY");
  STATION("Wick", "WCK");
  STATION("Wickford", "WIC");
  STATION("Wickham Market", "WCM");
  STATION("Widdrington", "WDD");
  STATION("Widnes", "WID");
  STATION("Widney Manor", "WMR");
  STATION("Wigan North Western", "WGN");
  STATION("Wigan Wallgate", "WGW");
  STATION("Wigton", "WGT");
  STATION("Wildmill", "WMI");
  STATION("Willesden Junction", "WIJ");
  STATION("Williamwood", "WLM");
  STATION("Willington", "WIL");
  STATION("Wilmcote", "WMC");
  STATION("Wilmslow", "WML");
  STATION("Wilnecote (Staffs)", "WNE");
  STATION("Wimbledon Chase", "WBO");
  STATION("Wimbledon", "WIM");
  STATION("Winchelsea", "WSE");
  STATION("Winchester", "WIN");
  STATION("Winchfield", "WNF");
  STATION("Winchmore Hill", "WIH");
  STATION("Windermere", "WDM");
  STATION("Windsor & Eton Central", "WNC");
  STATION("Windsor & Eton Riverside", "WNR");
  STATION("Winnersh Triangle", "WTI");
  STATION("Winnersh", "WNS");
  STATION("Winsford", "WSF");
  STATION("Wishaw", "WSH");
  STATION("Witham", "WTM");
  STATION("Witley", "WTY");
  STATION("Witton (West Midlands)", "WTT");
  STATION("Wivelsfield", "WVF");
  STATION("Wivenhoe", "WIV");
  STATION("Woburn Sands", "WOB");
  STATION("Woking", "WOK");
  STATION("Wokingham", "WKM");
  STATION("Woldingham", "WOH");
  STATION("Wolverhampton", "WVH");
  STATION("Wolverton", "WOL");
  STATION("Wombwell", "WOM");
  STATION("Wood End", "WDE");
  STATION("Wood Street", "WST");
  STATION("Woodbridge", "WDB");
  STATION("Woodgrange Park", "WGR");
  STATION("Woodhall", "WDL");
  STATION("Woodhouse", "WDH");
  STATION("Woodlesford", "WDS");
  STATION("Woodley", "WLY");
  STATION("Woodmansterne", "WME");
  STATION("Woodsmoor", "WSR");
  STATION("Wool", "WOO");
  STATION("Woolston", "WLS");
  STATION("Woolwich Arsenal", "WWA");
  STATION("Woolwich Dockyard", "WWD");
  STATION("Wootton Wawen", "WWW");
  STATION("Worcester Foregate Street", "WOF");
  STATION("Worcester Park", "WCP");
  STATION("Worcester Shrub Hill", "WOS");
  STATION("Worcestershire Parkway", "WOP");
  STATION("Workington", "WKG");
  STATION("Worksop", "WRK");
  STATION("Worle", "WOR");
  STATION("Worplesdon", "WPL");
  STATION("Worstead", "WRT");
  STATION("Worthing", "WRH");
  STATION("Wrabness", "WRB");
  STATION("Wraysbury", "WRY");
  STATION("Wrenbury", "WRE");
  STATION("Wressle", "WRS");
  STATION("Wrexham Central", "WXC");
  STATION("Wrexham General", "WRX");
  STATION("Wye", "WYE");
  STATION("Wylam", "WYM");
  STATION("Wylde Green", "WYL");
  STATION("Wymondham", "WMD");
  STATION("Wythall", "WYT");
  STATION("Yalding", "YAL");
  STATION("Yardley Wood", "YRD");
  STATION("Yarm", "YRM");
  STATION("Yate", "YAE");
  STATION("Yatton", "YAT");
  STATION("Yeoford", "YEO");
  STATION("Yeovil Junction", "YVJ");
  STATION("Yeovil Pen Mill", "YVP");
  STATION("Yetminster", "YET");
  STATION("Ynyswen", "YNW");
  STATION("Yoker", "YOK");
  STATION("York", "YRK");
  STATION("Yorton", "YRT");
  STATION("Ystrad Mynach", "YSM");
  STATION("Ystrad Rhondda", "YSR");
}
