#pragma once

#define VT "Avanti West Coast"
#define XC "Cross Country"
#define EM "East Midlands"
#define ES "Eurostar"
#define GN "Great Northern"
#define GW "Great Western Railway"
#define GR "London North Eastern Railway"
#define LD "Lumo (East Coast)"
#define LF "Lumo (West Coast)"
#define NT "Northern"
#define SR "ScotRail"
#define SW "South Western Railway"
#define TL "Thameslink"
#define TP "TransPennine Express"
#define AW "Transport for Wales"
#define LM "West Midlands Trains"
